// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: breath.proto
// Protobuf Java Version: 4.28.2

package oplus.pb;

public final class Breath {
  private Breath() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface SleepBreathDetailsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.heytap.wearable.health.SleepBreathDetails)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * 数据包索引
     * </pre>
     *
     * <code>uint32 index = 1;</code>
     * @return The index.
     */
    int getIndex();

    /**
     * <pre>
     * 数据包第一条数据的时间戳
     * </pre>
     *
     * <code>uint32 start_time = 2;</code>
     * @return The startTime.
     */
    int getStartTime();

    /**
     * <code>repeated .com.heytap.wearable.health.SleepBreath breaths = 3;</code>
     */
    java.util.List<oplus.pb.Breath.SleepBreath> 
        getBreathsList();
    /**
     * <code>repeated .com.heytap.wearable.health.SleepBreath breaths = 3;</code>
     */
    oplus.pb.Breath.SleepBreath getBreaths(int index);
    /**
     * <code>repeated .com.heytap.wearable.health.SleepBreath breaths = 3;</code>
     */
    int getBreathsCount();
  }
  /**
   * Protobuf type {@code com.heytap.wearable.health.SleepBreathDetails}
   */
  public  static final class SleepBreathDetails extends
      com.google.protobuf.GeneratedMessageLite<
          SleepBreathDetails, SleepBreathDetails.Builder> implements
      // @@protoc_insertion_point(message_implements:com.heytap.wearable.health.SleepBreathDetails)
      SleepBreathDetailsOrBuilder {
    private SleepBreathDetails() {
      breaths_ = emptyProtobufList();
    }
    public static final int INDEX_FIELD_NUMBER = 1;
    private int index_;
    /**
     * <pre>
     * 数据包索引
     * </pre>
     *
     * <code>uint32 index = 1;</code>
     * @return The index.
     */
    @java.lang.Override
    public int getIndex() {
      return index_;
    }
    /**
     * <pre>
     * 数据包索引
     * </pre>
     *
     * <code>uint32 index = 1;</code>
     * @param value The index to set.
     */
    private void setIndex(int value) {
      
      index_ = value;
    }
    /**
     * <pre>
     * 数据包索引
     * </pre>
     *
     * <code>uint32 index = 1;</code>
     */
    private void clearIndex() {

      index_ = 0;
    }

    public static final int START_TIME_FIELD_NUMBER = 2;
    private int startTime_;
    /**
     * <pre>
     * 数据包第一条数据的时间戳
     * </pre>
     *
     * <code>uint32 start_time = 2;</code>
     * @return The startTime.
     */
    @java.lang.Override
    public int getStartTime() {
      return startTime_;
    }
    /**
     * <pre>
     * 数据包第一条数据的时间戳
     * </pre>
     *
     * <code>uint32 start_time = 2;</code>
     * @param value The startTime to set.
     */
    private void setStartTime(int value) {
      
      startTime_ = value;
    }
    /**
     * <pre>
     * 数据包第一条数据的时间戳
     * </pre>
     *
     * <code>uint32 start_time = 2;</code>
     */
    private void clearStartTime() {

      startTime_ = 0;
    }

    public static final int BREATHS_FIELD_NUMBER = 3;
    private com.google.protobuf.Internal.ProtobufList<oplus.pb.Breath.SleepBreath> breaths_;
    /**
     * <code>repeated .com.heytap.wearable.health.SleepBreath breaths = 3;</code>
     */
    @java.lang.Override
    public java.util.List<oplus.pb.Breath.SleepBreath> getBreathsList() {
      return breaths_;
    }
    /**
     * <code>repeated .com.heytap.wearable.health.SleepBreath breaths = 3;</code>
     */
    public java.util.List<? extends oplus.pb.Breath.SleepBreathOrBuilder> 
        getBreathsOrBuilderList() {
      return breaths_;
    }
    /**
     * <code>repeated .com.heytap.wearable.health.SleepBreath breaths = 3;</code>
     */
    @java.lang.Override
    public int getBreathsCount() {
      return breaths_.size();
    }
    /**
     * <code>repeated .com.heytap.wearable.health.SleepBreath breaths = 3;</code>
     */
    @java.lang.Override
    public oplus.pb.Breath.SleepBreath getBreaths(int index) {
      return breaths_.get(index);
    }
    /**
     * <code>repeated .com.heytap.wearable.health.SleepBreath breaths = 3;</code>
     */
    public oplus.pb.Breath.SleepBreathOrBuilder getBreathsOrBuilder(
        int index) {
      return breaths_.get(index);
    }
    private void ensureBreathsIsMutable() {
      com.google.protobuf.Internal.ProtobufList<oplus.pb.Breath.SleepBreath> tmp = breaths_;
      if (!tmp.isModifiable()) {
        breaths_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <code>repeated .com.heytap.wearable.health.SleepBreath breaths = 3;</code>
     */
    private void setBreaths(
        int index, oplus.pb.Breath.SleepBreath value) {
      value.getClass();
  ensureBreathsIsMutable();
      breaths_.set(index, value);
    }
    /**
     * <code>repeated .com.heytap.wearable.health.SleepBreath breaths = 3;</code>
     */
    private void addBreaths(oplus.pb.Breath.SleepBreath value) {
      value.getClass();
  ensureBreathsIsMutable();
      breaths_.add(value);
    }
    /**
     * <code>repeated .com.heytap.wearable.health.SleepBreath breaths = 3;</code>
     */
    private void addBreaths(
        int index, oplus.pb.Breath.SleepBreath value) {
      value.getClass();
  ensureBreathsIsMutable();
      breaths_.add(index, value);
    }
    /**
     * <code>repeated .com.heytap.wearable.health.SleepBreath breaths = 3;</code>
     */
    private void addAllBreaths(
        java.lang.Iterable<? extends oplus.pb.Breath.SleepBreath> values) {
      ensureBreathsIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, breaths_);
    }
    /**
     * <code>repeated .com.heytap.wearable.health.SleepBreath breaths = 3;</code>
     */
    private void clearBreaths() {
      breaths_ = emptyProtobufList();
    }
    /**
     * <code>repeated .com.heytap.wearable.health.SleepBreath breaths = 3;</code>
     */
    private void removeBreaths(int index) {
      ensureBreathsIsMutable();
      breaths_.remove(index);
    }

    public static oplus.pb.Breath.SleepBreathDetails parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.Breath.SleepBreathDetails parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.Breath.SleepBreathDetails parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.Breath.SleepBreathDetails parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.Breath.SleepBreathDetails parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.Breath.SleepBreathDetails parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.Breath.SleepBreathDetails parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static oplus.pb.Breath.SleepBreathDetails parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static oplus.pb.Breath.SleepBreathDetails parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static oplus.pb.Breath.SleepBreathDetails parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static oplus.pb.Breath.SleepBreathDetails parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static oplus.pb.Breath.SleepBreathDetails parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(oplus.pb.Breath.SleepBreathDetails prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code com.heytap.wearable.health.SleepBreathDetails}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          oplus.pb.Breath.SleepBreathDetails, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.heytap.wearable.health.SleepBreathDetails)
        oplus.pb.Breath.SleepBreathDetailsOrBuilder {
      // Construct using oplus.pb.Breath.SleepBreathDetails.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * 数据包索引
       * </pre>
       *
       * <code>uint32 index = 1;</code>
       * @return The index.
       */
      @java.lang.Override
      public int getIndex() {
        return instance.getIndex();
      }
      /**
       * <pre>
       * 数据包索引
       * </pre>
       *
       * <code>uint32 index = 1;</code>
       * @param value The index to set.
       * @return This builder for chaining.
       */
      public Builder setIndex(int value) {
        copyOnWrite();
        instance.setIndex(value);
        return this;
      }
      /**
       * <pre>
       * 数据包索引
       * </pre>
       *
       * <code>uint32 index = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIndex() {
        copyOnWrite();
        instance.clearIndex();
        return this;
      }

      /**
       * <pre>
       * 数据包第一条数据的时间戳
       * </pre>
       *
       * <code>uint32 start_time = 2;</code>
       * @return The startTime.
       */
      @java.lang.Override
      public int getStartTime() {
        return instance.getStartTime();
      }
      /**
       * <pre>
       * 数据包第一条数据的时间戳
       * </pre>
       *
       * <code>uint32 start_time = 2;</code>
       * @param value The startTime to set.
       * @return This builder for chaining.
       */
      public Builder setStartTime(int value) {
        copyOnWrite();
        instance.setStartTime(value);
        return this;
      }
      /**
       * <pre>
       * 数据包第一条数据的时间戳
       * </pre>
       *
       * <code>uint32 start_time = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStartTime() {
        copyOnWrite();
        instance.clearStartTime();
        return this;
      }

      /**
       * <code>repeated .com.heytap.wearable.health.SleepBreath breaths = 3;</code>
       */
      @java.lang.Override
      public java.util.List<oplus.pb.Breath.SleepBreath> getBreathsList() {
        return java.util.Collections.unmodifiableList(
            instance.getBreathsList());
      }
      /**
       * <code>repeated .com.heytap.wearable.health.SleepBreath breaths = 3;</code>
       */
      @java.lang.Override
      public int getBreathsCount() {
        return instance.getBreathsCount();
      }/**
       * <code>repeated .com.heytap.wearable.health.SleepBreath breaths = 3;</code>
       */
      @java.lang.Override
      public oplus.pb.Breath.SleepBreath getBreaths(int index) {
        return instance.getBreaths(index);
      }
      /**
       * <code>repeated .com.heytap.wearable.health.SleepBreath breaths = 3;</code>
       */
      public Builder setBreaths(
          int index, oplus.pb.Breath.SleepBreath value) {
        copyOnWrite();
        instance.setBreaths(index, value);
        return this;
      }
      /**
       * <code>repeated .com.heytap.wearable.health.SleepBreath breaths = 3;</code>
       */
      public Builder setBreaths(
          int index, oplus.pb.Breath.SleepBreath.Builder builderForValue) {
        copyOnWrite();
        instance.setBreaths(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.heytap.wearable.health.SleepBreath breaths = 3;</code>
       */
      public Builder addBreaths(oplus.pb.Breath.SleepBreath value) {
        copyOnWrite();
        instance.addBreaths(value);
        return this;
      }
      /**
       * <code>repeated .com.heytap.wearable.health.SleepBreath breaths = 3;</code>
       */
      public Builder addBreaths(
          int index, oplus.pb.Breath.SleepBreath value) {
        copyOnWrite();
        instance.addBreaths(index, value);
        return this;
      }
      /**
       * <code>repeated .com.heytap.wearable.health.SleepBreath breaths = 3;</code>
       */
      public Builder addBreaths(
          oplus.pb.Breath.SleepBreath.Builder builderForValue) {
        copyOnWrite();
        instance.addBreaths(builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.heytap.wearable.health.SleepBreath breaths = 3;</code>
       */
      public Builder addBreaths(
          int index, oplus.pb.Breath.SleepBreath.Builder builderForValue) {
        copyOnWrite();
        instance.addBreaths(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.heytap.wearable.health.SleepBreath breaths = 3;</code>
       */
      public Builder addAllBreaths(
          java.lang.Iterable<? extends oplus.pb.Breath.SleepBreath> values) {
        copyOnWrite();
        instance.addAllBreaths(values);
        return this;
      }
      /**
       * <code>repeated .com.heytap.wearable.health.SleepBreath breaths = 3;</code>
       */
      public Builder clearBreaths() {
        copyOnWrite();
        instance.clearBreaths();
        return this;
      }
      /**
       * <code>repeated .com.heytap.wearable.health.SleepBreath breaths = 3;</code>
       */
      public Builder removeBreaths(int index) {
        copyOnWrite();
        instance.removeBreaths(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.heytap.wearable.health.SleepBreathDetails)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new oplus.pb.Breath.SleepBreathDetails();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "index_",
              "startTime_",
              "breaths_",
              oplus.pb.Breath.SleepBreath.class,
            };
            java.lang.String info =
                "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0001\u0000\u0001\u000b\u0002\u000b" +
                "\u0003\u001b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<oplus.pb.Breath.SleepBreathDetails> parser = PARSER;
          if (parser == null) {
            synchronized (oplus.pb.Breath.SleepBreathDetails.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<oplus.pb.Breath.SleepBreathDetails>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.heytap.wearable.health.SleepBreathDetails)
    private static final oplus.pb.Breath.SleepBreathDetails DEFAULT_INSTANCE;
    static {
      SleepBreathDetails defaultInstance = new SleepBreathDetails();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        SleepBreathDetails.class, defaultInstance);
    }

    public static oplus.pb.Breath.SleepBreathDetails getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<SleepBreathDetails> PARSER;

    public static com.google.protobuf.Parser<SleepBreathDetails> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface SleepBreathOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.heytap.wearable.health.SleepBreath)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * 每条数据时间戳相比第一条数据时间戳的分钟偏移量（单位分钟）
     * </pre>
     *
     * <code>uint32 min_offset = 1;</code>
     * @return The minOffset.
     */
    int getMinOffset();

    /**
     * <pre>
     * 呼吸率 0-1bit表示置信度，其他表示呼吸率
     * </pre>
     *
     * <code>uint32 breath = 2;</code>
     * @return The breath.
     */
    int getBreath();
  }
  /**
   * Protobuf type {@code com.heytap.wearable.health.SleepBreath}
   */
  public  static final class SleepBreath extends
      com.google.protobuf.GeneratedMessageLite<
          SleepBreath, SleepBreath.Builder> implements
      // @@protoc_insertion_point(message_implements:com.heytap.wearable.health.SleepBreath)
      SleepBreathOrBuilder {
    private SleepBreath() {
    }
    public static final int MIN_OFFSET_FIELD_NUMBER = 1;
    private int minOffset_;
    /**
     * <pre>
     * 每条数据时间戳相比第一条数据时间戳的分钟偏移量（单位分钟）
     * </pre>
     *
     * <code>uint32 min_offset = 1;</code>
     * @return The minOffset.
     */
    @java.lang.Override
    public int getMinOffset() {
      return minOffset_;
    }
    /**
     * <pre>
     * 每条数据时间戳相比第一条数据时间戳的分钟偏移量（单位分钟）
     * </pre>
     *
     * <code>uint32 min_offset = 1;</code>
     * @param value The minOffset to set.
     */
    private void setMinOffset(int value) {
      
      minOffset_ = value;
    }
    /**
     * <pre>
     * 每条数据时间戳相比第一条数据时间戳的分钟偏移量（单位分钟）
     * </pre>
     *
     * <code>uint32 min_offset = 1;</code>
     */
    private void clearMinOffset() {

      minOffset_ = 0;
    }

    public static final int BREATH_FIELD_NUMBER = 2;
    private int breath_;
    /**
     * <pre>
     * 呼吸率 0-1bit表示置信度，其他表示呼吸率
     * </pre>
     *
     * <code>uint32 breath = 2;</code>
     * @return The breath.
     */
    @java.lang.Override
    public int getBreath() {
      return breath_;
    }
    /**
     * <pre>
     * 呼吸率 0-1bit表示置信度，其他表示呼吸率
     * </pre>
     *
     * <code>uint32 breath = 2;</code>
     * @param value The breath to set.
     */
    private void setBreath(int value) {
      
      breath_ = value;
    }
    /**
     * <pre>
     * 呼吸率 0-1bit表示置信度，其他表示呼吸率
     * </pre>
     *
     * <code>uint32 breath = 2;</code>
     */
    private void clearBreath() {

      breath_ = 0;
    }

    public static oplus.pb.Breath.SleepBreath parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.Breath.SleepBreath parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.Breath.SleepBreath parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.Breath.SleepBreath parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.Breath.SleepBreath parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.Breath.SleepBreath parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.Breath.SleepBreath parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static oplus.pb.Breath.SleepBreath parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static oplus.pb.Breath.SleepBreath parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static oplus.pb.Breath.SleepBreath parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static oplus.pb.Breath.SleepBreath parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static oplus.pb.Breath.SleepBreath parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(oplus.pb.Breath.SleepBreath prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code com.heytap.wearable.health.SleepBreath}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          oplus.pb.Breath.SleepBreath, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.heytap.wearable.health.SleepBreath)
        oplus.pb.Breath.SleepBreathOrBuilder {
      // Construct using oplus.pb.Breath.SleepBreath.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * 每条数据时间戳相比第一条数据时间戳的分钟偏移量（单位分钟）
       * </pre>
       *
       * <code>uint32 min_offset = 1;</code>
       * @return The minOffset.
       */
      @java.lang.Override
      public int getMinOffset() {
        return instance.getMinOffset();
      }
      /**
       * <pre>
       * 每条数据时间戳相比第一条数据时间戳的分钟偏移量（单位分钟）
       * </pre>
       *
       * <code>uint32 min_offset = 1;</code>
       * @param value The minOffset to set.
       * @return This builder for chaining.
       */
      public Builder setMinOffset(int value) {
        copyOnWrite();
        instance.setMinOffset(value);
        return this;
      }
      /**
       * <pre>
       * 每条数据时间戳相比第一条数据时间戳的分钟偏移量（单位分钟）
       * </pre>
       *
       * <code>uint32 min_offset = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMinOffset() {
        copyOnWrite();
        instance.clearMinOffset();
        return this;
      }

      /**
       * <pre>
       * 呼吸率 0-1bit表示置信度，其他表示呼吸率
       * </pre>
       *
       * <code>uint32 breath = 2;</code>
       * @return The breath.
       */
      @java.lang.Override
      public int getBreath() {
        return instance.getBreath();
      }
      /**
       * <pre>
       * 呼吸率 0-1bit表示置信度，其他表示呼吸率
       * </pre>
       *
       * <code>uint32 breath = 2;</code>
       * @param value The breath to set.
       * @return This builder for chaining.
       */
      public Builder setBreath(int value) {
        copyOnWrite();
        instance.setBreath(value);
        return this;
      }
      /**
       * <pre>
       * 呼吸率 0-1bit表示置信度，其他表示呼吸率
       * </pre>
       *
       * <code>uint32 breath = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearBreath() {
        copyOnWrite();
        instance.clearBreath();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.heytap.wearable.health.SleepBreath)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new oplus.pb.Breath.SleepBreath();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "minOffset_",
              "breath_",
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u000b\u0002\u000b" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<oplus.pb.Breath.SleepBreath> parser = PARSER;
          if (parser == null) {
            synchronized (oplus.pb.Breath.SleepBreath.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<oplus.pb.Breath.SleepBreath>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.heytap.wearable.health.SleepBreath)
    private static final oplus.pb.Breath.SleepBreath DEFAULT_INSTANCE;
    static {
      SleepBreath defaultInstance = new SleepBreath();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        SleepBreath.class, defaultInstance);
    }

    public static oplus.pb.Breath.SleepBreath getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<SleepBreath> PARSER;

    public static com.google.protobuf.Parser<SleepBreath> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
