// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common.proto
// Protobuf Java Version: 4.28.2

package oplus.pb;

public final class Common {
  private Common() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface ErrorCodeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Common.ErrorCode)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>uint32 code = 1;</code>
     * @return The code.
     */
    int getCode();

    /**
     * <code>string extraData = 2;</code>
     * @return The extraData.
     */
    java.lang.String getExtraData();
    /**
     * <code>string extraData = 2;</code>
     * @return The bytes for extraData.
     */
    com.google.protobuf.ByteString
        getExtraDataBytes();
  }
  /**
   * Protobuf type {@code Common.ErrorCode}
   */
  public  static final class ErrorCode extends
      com.google.protobuf.GeneratedMessageLite<
          ErrorCode, ErrorCode.Builder> implements
      // @@protoc_insertion_point(message_implements:Common.ErrorCode)
      ErrorCodeOrBuilder {
    private ErrorCode() {
      extraData_ = "";
    }
    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <code>uint32 code = 1;</code>
     * @return The code.
     */
    @java.lang.Override
    public int getCode() {
      return code_;
    }
    /**
     * <code>uint32 code = 1;</code>
     * @param value The code to set.
     */
    private void setCode(int value) {
      
      code_ = value;
    }
    /**
     * <code>uint32 code = 1;</code>
     */
    private void clearCode() {

      code_ = 0;
    }

    public static final int EXTRADATA_FIELD_NUMBER = 2;
    private java.lang.String extraData_;
    /**
     * <code>string extraData = 2;</code>
     * @return The extraData.
     */
    @java.lang.Override
    public java.lang.String getExtraData() {
      return extraData_;
    }
    /**
     * <code>string extraData = 2;</code>
     * @return The bytes for extraData.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getExtraDataBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(extraData_);
    }
    /**
     * <code>string extraData = 2;</code>
     * @param value The extraData to set.
     */
    private void setExtraData(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      extraData_ = value;
    }
    /**
     * <code>string extraData = 2;</code>
     */
    private void clearExtraData() {

      extraData_ = getDefaultInstance().getExtraData();
    }
    /**
     * <code>string extraData = 2;</code>
     * @param value The bytes for extraData to set.
     */
    private void setExtraDataBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      extraData_ = value.toStringUtf8();

    }

    public static oplus.pb.Common.ErrorCode parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.Common.ErrorCode parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.Common.ErrorCode parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.Common.ErrorCode parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.Common.ErrorCode parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.Common.ErrorCode parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.Common.ErrorCode parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static oplus.pb.Common.ErrorCode parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static oplus.pb.Common.ErrorCode parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static oplus.pb.Common.ErrorCode parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static oplus.pb.Common.ErrorCode parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static oplus.pb.Common.ErrorCode parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(oplus.pb.Common.ErrorCode prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code Common.ErrorCode}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          oplus.pb.Common.ErrorCode, Builder> implements
        // @@protoc_insertion_point(builder_implements:Common.ErrorCode)
        oplus.pb.Common.ErrorCodeOrBuilder {
      // Construct using oplus.pb.Common.ErrorCode.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>uint32 code = 1;</code>
       * @return The code.
       */
      @java.lang.Override
      public int getCode() {
        return instance.getCode();
      }
      /**
       * <code>uint32 code = 1;</code>
       * @param value The code to set.
       * @return This builder for chaining.
       */
      public Builder setCode(int value) {
        copyOnWrite();
        instance.setCode(value);
        return this;
      }
      /**
       * <code>uint32 code = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCode() {
        copyOnWrite();
        instance.clearCode();
        return this;
      }

      /**
       * <code>string extraData = 2;</code>
       * @return The extraData.
       */
      @java.lang.Override
      public java.lang.String getExtraData() {
        return instance.getExtraData();
      }
      /**
       * <code>string extraData = 2;</code>
       * @return The bytes for extraData.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getExtraDataBytes() {
        return instance.getExtraDataBytes();
      }
      /**
       * <code>string extraData = 2;</code>
       * @param value The extraData to set.
       * @return This builder for chaining.
       */
      public Builder setExtraData(
          java.lang.String value) {
        copyOnWrite();
        instance.setExtraData(value);
        return this;
      }
      /**
       * <code>string extraData = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearExtraData() {
        copyOnWrite();
        instance.clearExtraData();
        return this;
      }
      /**
       * <code>string extraData = 2;</code>
       * @param value The bytes for extraData to set.
       * @return This builder for chaining.
       */
      public Builder setExtraDataBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setExtraDataBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Common.ErrorCode)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new oplus.pb.Common.ErrorCode();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "code_",
              "extraData_",
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u000b\u0002\u0208" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<oplus.pb.Common.ErrorCode> parser = PARSER;
          if (parser == null) {
            synchronized (oplus.pb.Common.ErrorCode.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<oplus.pb.Common.ErrorCode>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:Common.ErrorCode)
    private static final oplus.pb.Common.ErrorCode DEFAULT_INSTANCE;
    static {
      ErrorCode defaultInstance = new ErrorCode();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        ErrorCode.class, defaultInstance);
    }

    public static oplus.pb.Common.ErrorCode getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ErrorCode> PARSER;

    public static com.google.protobuf.Parser<ErrorCode> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface AppIntentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Common.AppIntent)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string packageName = 1;</code>
     * @return The packageName.
     */
    java.lang.String getPackageName();
    /**
     * <code>string packageName = 1;</code>
     * @return The bytes for packageName.
     */
    com.google.protobuf.ByteString
        getPackageNameBytes();

    /**
     * <code>string action = 2;</code>
     * @return The action.
     */
    java.lang.String getAction();
    /**
     * <code>string action = 2;</code>
     * @return The bytes for action.
     */
    com.google.protobuf.ByteString
        getActionBytes();

    /**
     * <code>string params = 3;</code>
     * @return The params.
     */
    java.lang.String getParams();
    /**
     * <code>string params = 3;</code>
     * @return The bytes for params.
     */
    com.google.protobuf.ByteString
        getParamsBytes();

    /**
     * <code>string clsName = 4;</code>
     * @return The clsName.
     */
    java.lang.String getClsName();
    /**
     * <code>string clsName = 4;</code>
     * @return The bytes for clsName.
     */
    com.google.protobuf.ByteString
        getClsNameBytes();
  }
  /**
   * Protobuf type {@code Common.AppIntent}
   */
  public  static final class AppIntent extends
      com.google.protobuf.GeneratedMessageLite<
          AppIntent, AppIntent.Builder> implements
      // @@protoc_insertion_point(message_implements:Common.AppIntent)
      AppIntentOrBuilder {
    private AppIntent() {
      packageName_ = "";
      action_ = "";
      params_ = "";
      clsName_ = "";
    }
    public static final int PACKAGENAME_FIELD_NUMBER = 1;
    private java.lang.String packageName_;
    /**
     * <code>string packageName = 1;</code>
     * @return The packageName.
     */
    @java.lang.Override
    public java.lang.String getPackageName() {
      return packageName_;
    }
    /**
     * <code>string packageName = 1;</code>
     * @return The bytes for packageName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPackageNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(packageName_);
    }
    /**
     * <code>string packageName = 1;</code>
     * @param value The packageName to set.
     */
    private void setPackageName(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      packageName_ = value;
    }
    /**
     * <code>string packageName = 1;</code>
     */
    private void clearPackageName() {

      packageName_ = getDefaultInstance().getPackageName();
    }
    /**
     * <code>string packageName = 1;</code>
     * @param value The bytes for packageName to set.
     */
    private void setPackageNameBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      packageName_ = value.toStringUtf8();

    }

    public static final int ACTION_FIELD_NUMBER = 2;
    private java.lang.String action_;
    /**
     * <code>string action = 2;</code>
     * @return The action.
     */
    @java.lang.Override
    public java.lang.String getAction() {
      return action_;
    }
    /**
     * <code>string action = 2;</code>
     * @return The bytes for action.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getActionBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(action_);
    }
    /**
     * <code>string action = 2;</code>
     * @param value The action to set.
     */
    private void setAction(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      action_ = value;
    }
    /**
     * <code>string action = 2;</code>
     */
    private void clearAction() {

      action_ = getDefaultInstance().getAction();
    }
    /**
     * <code>string action = 2;</code>
     * @param value The bytes for action to set.
     */
    private void setActionBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      action_ = value.toStringUtf8();

    }

    public static final int PARAMS_FIELD_NUMBER = 3;
    private java.lang.String params_;
    /**
     * <code>string params = 3;</code>
     * @return The params.
     */
    @java.lang.Override
    public java.lang.String getParams() {
      return params_;
    }
    /**
     * <code>string params = 3;</code>
     * @return The bytes for params.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getParamsBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(params_);
    }
    /**
     * <code>string params = 3;</code>
     * @param value The params to set.
     */
    private void setParams(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      params_ = value;
    }
    /**
     * <code>string params = 3;</code>
     */
    private void clearParams() {

      params_ = getDefaultInstance().getParams();
    }
    /**
     * <code>string params = 3;</code>
     * @param value The bytes for params to set.
     */
    private void setParamsBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      params_ = value.toStringUtf8();

    }

    public static final int CLSNAME_FIELD_NUMBER = 4;
    private java.lang.String clsName_;
    /**
     * <code>string clsName = 4;</code>
     * @return The clsName.
     */
    @java.lang.Override
    public java.lang.String getClsName() {
      return clsName_;
    }
    /**
     * <code>string clsName = 4;</code>
     * @return The bytes for clsName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getClsNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(clsName_);
    }
    /**
     * <code>string clsName = 4;</code>
     * @param value The clsName to set.
     */
    private void setClsName(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      clsName_ = value;
    }
    /**
     * <code>string clsName = 4;</code>
     */
    private void clearClsName() {

      clsName_ = getDefaultInstance().getClsName();
    }
    /**
     * <code>string clsName = 4;</code>
     * @param value The bytes for clsName to set.
     */
    private void setClsNameBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      clsName_ = value.toStringUtf8();

    }

    public static oplus.pb.Common.AppIntent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.Common.AppIntent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.Common.AppIntent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.Common.AppIntent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.Common.AppIntent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.Common.AppIntent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.Common.AppIntent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static oplus.pb.Common.AppIntent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static oplus.pb.Common.AppIntent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static oplus.pb.Common.AppIntent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static oplus.pb.Common.AppIntent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static oplus.pb.Common.AppIntent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(oplus.pb.Common.AppIntent prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code Common.AppIntent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          oplus.pb.Common.AppIntent, Builder> implements
        // @@protoc_insertion_point(builder_implements:Common.AppIntent)
        oplus.pb.Common.AppIntentOrBuilder {
      // Construct using oplus.pb.Common.AppIntent.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string packageName = 1;</code>
       * @return The packageName.
       */
      @java.lang.Override
      public java.lang.String getPackageName() {
        return instance.getPackageName();
      }
      /**
       * <code>string packageName = 1;</code>
       * @return The bytes for packageName.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getPackageNameBytes() {
        return instance.getPackageNameBytes();
      }
      /**
       * <code>string packageName = 1;</code>
       * @param value The packageName to set.
       * @return This builder for chaining.
       */
      public Builder setPackageName(
          java.lang.String value) {
        copyOnWrite();
        instance.setPackageName(value);
        return this;
      }
      /**
       * <code>string packageName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPackageName() {
        copyOnWrite();
        instance.clearPackageName();
        return this;
      }
      /**
       * <code>string packageName = 1;</code>
       * @param value The bytes for packageName to set.
       * @return This builder for chaining.
       */
      public Builder setPackageNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPackageNameBytes(value);
        return this;
      }

      /**
       * <code>string action = 2;</code>
       * @return The action.
       */
      @java.lang.Override
      public java.lang.String getAction() {
        return instance.getAction();
      }
      /**
       * <code>string action = 2;</code>
       * @return The bytes for action.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getActionBytes() {
        return instance.getActionBytes();
      }
      /**
       * <code>string action = 2;</code>
       * @param value The action to set.
       * @return This builder for chaining.
       */
      public Builder setAction(
          java.lang.String value) {
        copyOnWrite();
        instance.setAction(value);
        return this;
      }
      /**
       * <code>string action = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAction() {
        copyOnWrite();
        instance.clearAction();
        return this;
      }
      /**
       * <code>string action = 2;</code>
       * @param value The bytes for action to set.
       * @return This builder for chaining.
       */
      public Builder setActionBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setActionBytes(value);
        return this;
      }

      /**
       * <code>string params = 3;</code>
       * @return The params.
       */
      @java.lang.Override
      public java.lang.String getParams() {
        return instance.getParams();
      }
      /**
       * <code>string params = 3;</code>
       * @return The bytes for params.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getParamsBytes() {
        return instance.getParamsBytes();
      }
      /**
       * <code>string params = 3;</code>
       * @param value The params to set.
       * @return This builder for chaining.
       */
      public Builder setParams(
          java.lang.String value) {
        copyOnWrite();
        instance.setParams(value);
        return this;
      }
      /**
       * <code>string params = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearParams() {
        copyOnWrite();
        instance.clearParams();
        return this;
      }
      /**
       * <code>string params = 3;</code>
       * @param value The bytes for params to set.
       * @return This builder for chaining.
       */
      public Builder setParamsBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setParamsBytes(value);
        return this;
      }

      /**
       * <code>string clsName = 4;</code>
       * @return The clsName.
       */
      @java.lang.Override
      public java.lang.String getClsName() {
        return instance.getClsName();
      }
      /**
       * <code>string clsName = 4;</code>
       * @return The bytes for clsName.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getClsNameBytes() {
        return instance.getClsNameBytes();
      }
      /**
       * <code>string clsName = 4;</code>
       * @param value The clsName to set.
       * @return This builder for chaining.
       */
      public Builder setClsName(
          java.lang.String value) {
        copyOnWrite();
        instance.setClsName(value);
        return this;
      }
      /**
       * <code>string clsName = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearClsName() {
        copyOnWrite();
        instance.clearClsName();
        return this;
      }
      /**
       * <code>string clsName = 4;</code>
       * @param value The bytes for clsName to set.
       * @return This builder for chaining.
       */
      public Builder setClsNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setClsNameBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Common.AppIntent)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new oplus.pb.Common.AppIntent();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "packageName_",
              "action_",
              "params_",
              "clsName_",
            };
            java.lang.String info =
                "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
                "\u0003\u0208\u0004\u0208";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<oplus.pb.Common.AppIntent> parser = PARSER;
          if (parser == null) {
            synchronized (oplus.pb.Common.AppIntent.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<oplus.pb.Common.AppIntent>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:Common.AppIntent)
    private static final oplus.pb.Common.AppIntent DEFAULT_INSTANCE;
    static {
      AppIntent defaultInstance = new AppIntent();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        AppIntent.class, defaultInstance);
    }

    public static oplus.pb.Common.AppIntent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<AppIntent> PARSER;

    public static com.google.protobuf.Parser<AppIntent> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface PacketRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Common.PacketRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>uint32 startTime = 1;</code>
     * @return The startTime.
     */
    int getStartTime();

    /**
     * <code>uint32 endTime = 2;</code>
     * @return The endTime.
     */
    int getEndTime();
  }
  /**
   * Protobuf type {@code Common.PacketRequest}
   */
  public  static final class PacketRequest extends
      com.google.protobuf.GeneratedMessageLite<
          PacketRequest, PacketRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:Common.PacketRequest)
      PacketRequestOrBuilder {
    private PacketRequest() {
    }
    public static final int STARTTIME_FIELD_NUMBER = 1;
    private int startTime_;
    /**
     * <code>uint32 startTime = 1;</code>
     * @return The startTime.
     */
    @java.lang.Override
    public int getStartTime() {
      return startTime_;
    }
    /**
     * <code>uint32 startTime = 1;</code>
     * @param value The startTime to set.
     */
    private void setStartTime(int value) {
      
      startTime_ = value;
    }
    /**
     * <code>uint32 startTime = 1;</code>
     */
    private void clearStartTime() {

      startTime_ = 0;
    }

    public static final int ENDTIME_FIELD_NUMBER = 2;
    private int endTime_;
    /**
     * <code>uint32 endTime = 2;</code>
     * @return The endTime.
     */
    @java.lang.Override
    public int getEndTime() {
      return endTime_;
    }
    /**
     * <code>uint32 endTime = 2;</code>
     * @param value The endTime to set.
     */
    private void setEndTime(int value) {
      
      endTime_ = value;
    }
    /**
     * <code>uint32 endTime = 2;</code>
     */
    private void clearEndTime() {

      endTime_ = 0;
    }

    public static oplus.pb.Common.PacketRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.Common.PacketRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.Common.PacketRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.Common.PacketRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.Common.PacketRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.Common.PacketRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.Common.PacketRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static oplus.pb.Common.PacketRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static oplus.pb.Common.PacketRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static oplus.pb.Common.PacketRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static oplus.pb.Common.PacketRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static oplus.pb.Common.PacketRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(oplus.pb.Common.PacketRequest prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code Common.PacketRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          oplus.pb.Common.PacketRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:Common.PacketRequest)
        oplus.pb.Common.PacketRequestOrBuilder {
      // Construct using oplus.pb.Common.PacketRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>uint32 startTime = 1;</code>
       * @return The startTime.
       */
      @java.lang.Override
      public int getStartTime() {
        return instance.getStartTime();
      }
      /**
       * <code>uint32 startTime = 1;</code>
       * @param value The startTime to set.
       * @return This builder for chaining.
       */
      public Builder setStartTime(int value) {
        copyOnWrite();
        instance.setStartTime(value);
        return this;
      }
      /**
       * <code>uint32 startTime = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStartTime() {
        copyOnWrite();
        instance.clearStartTime();
        return this;
      }

      /**
       * <code>uint32 endTime = 2;</code>
       * @return The endTime.
       */
      @java.lang.Override
      public int getEndTime() {
        return instance.getEndTime();
      }
      /**
       * <code>uint32 endTime = 2;</code>
       * @param value The endTime to set.
       * @return This builder for chaining.
       */
      public Builder setEndTime(int value) {
        copyOnWrite();
        instance.setEndTime(value);
        return this;
      }
      /**
       * <code>uint32 endTime = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearEndTime() {
        copyOnWrite();
        instance.clearEndTime();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Common.PacketRequest)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new oplus.pb.Common.PacketRequest();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "startTime_",
              "endTime_",
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u000b\u0002\u000b" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<oplus.pb.Common.PacketRequest> parser = PARSER;
          if (parser == null) {
            synchronized (oplus.pb.Common.PacketRequest.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<oplus.pb.Common.PacketRequest>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:Common.PacketRequest)
    private static final oplus.pb.Common.PacketRequest DEFAULT_INSTANCE;
    static {
      PacketRequest defaultInstance = new PacketRequest();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        PacketRequest.class, defaultInstance);
    }

    public static oplus.pb.Common.PacketRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<PacketRequest> PARSER;

    public static com.google.protobuf.Parser<PacketRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface PacketResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Common.PacketResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>uint32 packageTotal = 1;</code>
     * @return The packageTotal.
     */
    int getPackageTotal();

    /**
     * <code>uint32 startTime = 2;</code>
     * @return The startTime.
     */
    int getStartTime();

    /**
     * <code>uint32 maxDay = 3;</code>
     * @return The maxDay.
     */
    int getMaxDay();
  }
  /**
   * Protobuf type {@code Common.PacketResponse}
   */
  public  static final class PacketResponse extends
      com.google.protobuf.GeneratedMessageLite<
          PacketResponse, PacketResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:Common.PacketResponse)
      PacketResponseOrBuilder {
    private PacketResponse() {
    }
    public static final int PACKAGETOTAL_FIELD_NUMBER = 1;
    private int packageTotal_;
    /**
     * <code>uint32 packageTotal = 1;</code>
     * @return The packageTotal.
     */
    @java.lang.Override
    public int getPackageTotal() {
      return packageTotal_;
    }
    /**
     * <code>uint32 packageTotal = 1;</code>
     * @param value The packageTotal to set.
     */
    private void setPackageTotal(int value) {
      
      packageTotal_ = value;
    }
    /**
     * <code>uint32 packageTotal = 1;</code>
     */
    private void clearPackageTotal() {

      packageTotal_ = 0;
    }

    public static final int STARTTIME_FIELD_NUMBER = 2;
    private int startTime_;
    /**
     * <code>uint32 startTime = 2;</code>
     * @return The startTime.
     */
    @java.lang.Override
    public int getStartTime() {
      return startTime_;
    }
    /**
     * <code>uint32 startTime = 2;</code>
     * @param value The startTime to set.
     */
    private void setStartTime(int value) {
      
      startTime_ = value;
    }
    /**
     * <code>uint32 startTime = 2;</code>
     */
    private void clearStartTime() {

      startTime_ = 0;
    }

    public static final int MAXDAY_FIELD_NUMBER = 3;
    private int maxDay_;
    /**
     * <code>uint32 maxDay = 3;</code>
     * @return The maxDay.
     */
    @java.lang.Override
    public int getMaxDay() {
      return maxDay_;
    }
    /**
     * <code>uint32 maxDay = 3;</code>
     * @param value The maxDay to set.
     */
    private void setMaxDay(int value) {
      
      maxDay_ = value;
    }
    /**
     * <code>uint32 maxDay = 3;</code>
     */
    private void clearMaxDay() {

      maxDay_ = 0;
    }

    public static oplus.pb.Common.PacketResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.Common.PacketResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.Common.PacketResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.Common.PacketResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.Common.PacketResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.Common.PacketResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.Common.PacketResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static oplus.pb.Common.PacketResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static oplus.pb.Common.PacketResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static oplus.pb.Common.PacketResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static oplus.pb.Common.PacketResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static oplus.pb.Common.PacketResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(oplus.pb.Common.PacketResponse prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code Common.PacketResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          oplus.pb.Common.PacketResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:Common.PacketResponse)
        oplus.pb.Common.PacketResponseOrBuilder {
      // Construct using oplus.pb.Common.PacketResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>uint32 packageTotal = 1;</code>
       * @return The packageTotal.
       */
      @java.lang.Override
      public int getPackageTotal() {
        return instance.getPackageTotal();
      }
      /**
       * <code>uint32 packageTotal = 1;</code>
       * @param value The packageTotal to set.
       * @return This builder for chaining.
       */
      public Builder setPackageTotal(int value) {
        copyOnWrite();
        instance.setPackageTotal(value);
        return this;
      }
      /**
       * <code>uint32 packageTotal = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPackageTotal() {
        copyOnWrite();
        instance.clearPackageTotal();
        return this;
      }

      /**
       * <code>uint32 startTime = 2;</code>
       * @return The startTime.
       */
      @java.lang.Override
      public int getStartTime() {
        return instance.getStartTime();
      }
      /**
       * <code>uint32 startTime = 2;</code>
       * @param value The startTime to set.
       * @return This builder for chaining.
       */
      public Builder setStartTime(int value) {
        copyOnWrite();
        instance.setStartTime(value);
        return this;
      }
      /**
       * <code>uint32 startTime = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStartTime() {
        copyOnWrite();
        instance.clearStartTime();
        return this;
      }

      /**
       * <code>uint32 maxDay = 3;</code>
       * @return The maxDay.
       */
      @java.lang.Override
      public int getMaxDay() {
        return instance.getMaxDay();
      }
      /**
       * <code>uint32 maxDay = 3;</code>
       * @param value The maxDay to set.
       * @return This builder for chaining.
       */
      public Builder setMaxDay(int value) {
        copyOnWrite();
        instance.setMaxDay(value);
        return this;
      }
      /**
       * <code>uint32 maxDay = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMaxDay() {
        copyOnWrite();
        instance.clearMaxDay();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Common.PacketResponse)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new oplus.pb.Common.PacketResponse();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "packageTotal_",
              "startTime_",
              "maxDay_",
            };
            java.lang.String info =
                "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u000b\u0002\u000b" +
                "\u0003\u000b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<oplus.pb.Common.PacketResponse> parser = PARSER;
          if (parser == null) {
            synchronized (oplus.pb.Common.PacketResponse.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<oplus.pb.Common.PacketResponse>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:Common.PacketResponse)
    private static final oplus.pb.Common.PacketResponse DEFAULT_INSTANCE;
    static {
      PacketResponse defaultInstance = new PacketResponse();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        PacketResponse.class, defaultInstance);
    }

    public static oplus.pb.Common.PacketResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<PacketResponse> PARSER;

    public static com.google.protobuf.Parser<PacketResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface PacketDataRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Common.PacketDataRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>uint32 index = 1;</code>
     * @return The index.
     */
    int getIndex();

    /**
     * <code>uint32 startTime = 2;</code>
     * @return The startTime.
     */
    int getStartTime();
  }
  /**
   * Protobuf type {@code Common.PacketDataRequest}
   */
  public  static final class PacketDataRequest extends
      com.google.protobuf.GeneratedMessageLite<
          PacketDataRequest, PacketDataRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:Common.PacketDataRequest)
      PacketDataRequestOrBuilder {
    private PacketDataRequest() {
    }
    public static final int INDEX_FIELD_NUMBER = 1;
    private int index_;
    /**
     * <code>uint32 index = 1;</code>
     * @return The index.
     */
    @java.lang.Override
    public int getIndex() {
      return index_;
    }
    /**
     * <code>uint32 index = 1;</code>
     * @param value The index to set.
     */
    private void setIndex(int value) {
      
      index_ = value;
    }
    /**
     * <code>uint32 index = 1;</code>
     */
    private void clearIndex() {

      index_ = 0;
    }

    public static final int STARTTIME_FIELD_NUMBER = 2;
    private int startTime_;
    /**
     * <code>uint32 startTime = 2;</code>
     * @return The startTime.
     */
    @java.lang.Override
    public int getStartTime() {
      return startTime_;
    }
    /**
     * <code>uint32 startTime = 2;</code>
     * @param value The startTime to set.
     */
    private void setStartTime(int value) {
      
      startTime_ = value;
    }
    /**
     * <code>uint32 startTime = 2;</code>
     */
    private void clearStartTime() {

      startTime_ = 0;
    }

    public static oplus.pb.Common.PacketDataRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.Common.PacketDataRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.Common.PacketDataRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.Common.PacketDataRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.Common.PacketDataRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.Common.PacketDataRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.Common.PacketDataRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static oplus.pb.Common.PacketDataRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static oplus.pb.Common.PacketDataRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static oplus.pb.Common.PacketDataRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static oplus.pb.Common.PacketDataRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static oplus.pb.Common.PacketDataRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(oplus.pb.Common.PacketDataRequest prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code Common.PacketDataRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          oplus.pb.Common.PacketDataRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:Common.PacketDataRequest)
        oplus.pb.Common.PacketDataRequestOrBuilder {
      // Construct using oplus.pb.Common.PacketDataRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>uint32 index = 1;</code>
       * @return The index.
       */
      @java.lang.Override
      public int getIndex() {
        return instance.getIndex();
      }
      /**
       * <code>uint32 index = 1;</code>
       * @param value The index to set.
       * @return This builder for chaining.
       */
      public Builder setIndex(int value) {
        copyOnWrite();
        instance.setIndex(value);
        return this;
      }
      /**
       * <code>uint32 index = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIndex() {
        copyOnWrite();
        instance.clearIndex();
        return this;
      }

      /**
       * <code>uint32 startTime = 2;</code>
       * @return The startTime.
       */
      @java.lang.Override
      public int getStartTime() {
        return instance.getStartTime();
      }
      /**
       * <code>uint32 startTime = 2;</code>
       * @param value The startTime to set.
       * @return This builder for chaining.
       */
      public Builder setStartTime(int value) {
        copyOnWrite();
        instance.setStartTime(value);
        return this;
      }
      /**
       * <code>uint32 startTime = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStartTime() {
        copyOnWrite();
        instance.clearStartTime();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Common.PacketDataRequest)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new oplus.pb.Common.PacketDataRequest();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "index_",
              "startTime_",
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u000b\u0002\u000b" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<oplus.pb.Common.PacketDataRequest> parser = PARSER;
          if (parser == null) {
            synchronized (oplus.pb.Common.PacketDataRequest.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<oplus.pb.Common.PacketDataRequest>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:Common.PacketDataRequest)
    private static final oplus.pb.Common.PacketDataRequest DEFAULT_INSTANCE;
    static {
      PacketDataRequest defaultInstance = new PacketDataRequest();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        PacketDataRequest.class, defaultInstance);
    }

    public static oplus.pb.Common.PacketDataRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<PacketDataRequest> PARSER;

    public static com.google.protobuf.Parser<PacketDataRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface DataChangedNotifyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Common.DataChangedNotify)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>uint32 dataType = 1;</code>
     * @return The dataType.
     */
    int getDataType();

    /**
     * <code>uint32 dataChangedTime = 2;</code>
     * @return The dataChangedTime.
     */
    int getDataChangedTime();

    /**
     * <code>string extra = 3;</code>
     * @return The extra.
     */
    java.lang.String getExtra();
    /**
     * <code>string extra = 3;</code>
     * @return The bytes for extra.
     */
    com.google.protobuf.ByteString
        getExtraBytes();
  }
  /**
   * Protobuf type {@code Common.DataChangedNotify}
   */
  public  static final class DataChangedNotify extends
      com.google.protobuf.GeneratedMessageLite<
          DataChangedNotify, DataChangedNotify.Builder> implements
      // @@protoc_insertion_point(message_implements:Common.DataChangedNotify)
      DataChangedNotifyOrBuilder {
    private DataChangedNotify() {
      extra_ = "";
    }
    public static final int DATATYPE_FIELD_NUMBER = 1;
    private int dataType_;
    /**
     * <code>uint32 dataType = 1;</code>
     * @return The dataType.
     */
    @java.lang.Override
    public int getDataType() {
      return dataType_;
    }
    /**
     * <code>uint32 dataType = 1;</code>
     * @param value The dataType to set.
     */
    private void setDataType(int value) {
      
      dataType_ = value;
    }
    /**
     * <code>uint32 dataType = 1;</code>
     */
    private void clearDataType() {

      dataType_ = 0;
    }

    public static final int DATACHANGEDTIME_FIELD_NUMBER = 2;
    private int dataChangedTime_;
    /**
     * <code>uint32 dataChangedTime = 2;</code>
     * @return The dataChangedTime.
     */
    @java.lang.Override
    public int getDataChangedTime() {
      return dataChangedTime_;
    }
    /**
     * <code>uint32 dataChangedTime = 2;</code>
     * @param value The dataChangedTime to set.
     */
    private void setDataChangedTime(int value) {
      
      dataChangedTime_ = value;
    }
    /**
     * <code>uint32 dataChangedTime = 2;</code>
     */
    private void clearDataChangedTime() {

      dataChangedTime_ = 0;
    }

    public static final int EXTRA_FIELD_NUMBER = 3;
    private java.lang.String extra_;
    /**
     * <code>string extra = 3;</code>
     * @return The extra.
     */
    @java.lang.Override
    public java.lang.String getExtra() {
      return extra_;
    }
    /**
     * <code>string extra = 3;</code>
     * @return The bytes for extra.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getExtraBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(extra_);
    }
    /**
     * <code>string extra = 3;</code>
     * @param value The extra to set.
     */
    private void setExtra(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      extra_ = value;
    }
    /**
     * <code>string extra = 3;</code>
     */
    private void clearExtra() {

      extra_ = getDefaultInstance().getExtra();
    }
    /**
     * <code>string extra = 3;</code>
     * @param value The bytes for extra to set.
     */
    private void setExtraBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      extra_ = value.toStringUtf8();

    }

    public static oplus.pb.Common.DataChangedNotify parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.Common.DataChangedNotify parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.Common.DataChangedNotify parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.Common.DataChangedNotify parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.Common.DataChangedNotify parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.Common.DataChangedNotify parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.Common.DataChangedNotify parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static oplus.pb.Common.DataChangedNotify parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static oplus.pb.Common.DataChangedNotify parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static oplus.pb.Common.DataChangedNotify parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static oplus.pb.Common.DataChangedNotify parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static oplus.pb.Common.DataChangedNotify parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(oplus.pb.Common.DataChangedNotify prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code Common.DataChangedNotify}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          oplus.pb.Common.DataChangedNotify, Builder> implements
        // @@protoc_insertion_point(builder_implements:Common.DataChangedNotify)
        oplus.pb.Common.DataChangedNotifyOrBuilder {
      // Construct using oplus.pb.Common.DataChangedNotify.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>uint32 dataType = 1;</code>
       * @return The dataType.
       */
      @java.lang.Override
      public int getDataType() {
        return instance.getDataType();
      }
      /**
       * <code>uint32 dataType = 1;</code>
       * @param value The dataType to set.
       * @return This builder for chaining.
       */
      public Builder setDataType(int value) {
        copyOnWrite();
        instance.setDataType(value);
        return this;
      }
      /**
       * <code>uint32 dataType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDataType() {
        copyOnWrite();
        instance.clearDataType();
        return this;
      }

      /**
       * <code>uint32 dataChangedTime = 2;</code>
       * @return The dataChangedTime.
       */
      @java.lang.Override
      public int getDataChangedTime() {
        return instance.getDataChangedTime();
      }
      /**
       * <code>uint32 dataChangedTime = 2;</code>
       * @param value The dataChangedTime to set.
       * @return This builder for chaining.
       */
      public Builder setDataChangedTime(int value) {
        copyOnWrite();
        instance.setDataChangedTime(value);
        return this;
      }
      /**
       * <code>uint32 dataChangedTime = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDataChangedTime() {
        copyOnWrite();
        instance.clearDataChangedTime();
        return this;
      }

      /**
       * <code>string extra = 3;</code>
       * @return The extra.
       */
      @java.lang.Override
      public java.lang.String getExtra() {
        return instance.getExtra();
      }
      /**
       * <code>string extra = 3;</code>
       * @return The bytes for extra.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getExtraBytes() {
        return instance.getExtraBytes();
      }
      /**
       * <code>string extra = 3;</code>
       * @param value The extra to set.
       * @return This builder for chaining.
       */
      public Builder setExtra(
          java.lang.String value) {
        copyOnWrite();
        instance.setExtra(value);
        return this;
      }
      /**
       * <code>string extra = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearExtra() {
        copyOnWrite();
        instance.clearExtra();
        return this;
      }
      /**
       * <code>string extra = 3;</code>
       * @param value The bytes for extra to set.
       * @return This builder for chaining.
       */
      public Builder setExtraBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setExtraBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Common.DataChangedNotify)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new oplus.pb.Common.DataChangedNotify();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "dataType_",
              "dataChangedTime_",
              "extra_",
            };
            java.lang.String info =
                "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u000b\u0002\u000b" +
                "\u0003\u0208";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<oplus.pb.Common.DataChangedNotify> parser = PARSER;
          if (parser == null) {
            synchronized (oplus.pb.Common.DataChangedNotify.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<oplus.pb.Common.DataChangedNotify>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:Common.DataChangedNotify)
    private static final oplus.pb.Common.DataChangedNotify DEFAULT_INSTANCE;
    static {
      DataChangedNotify defaultInstance = new DataChangedNotify();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        DataChangedNotify.class, defaultInstance);
    }

    public static oplus.pb.Common.DataChangedNotify getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<DataChangedNotify> PARSER;

    public static com.google.protobuf.Parser<DataChangedNotify> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
