// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: fc.proto
// Protobuf Java Version: 4.28.2

package oplus.pb;

public final class Fc {
  private Fc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface FcDetailDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.heytap.wearable.health.FcDetailData)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>uint32 index = 1;</code>
     * @return The index.
     */
    int getIndex();

    /**
     * <pre>
     * 第一条数据的开始时间，时间戳（单位秒）
     * </pre>
     *
     * <code>uint32 start_time = 2;</code>
     * @return The startTime.
     */
    int getStartTime();

    /**
     * <pre>
     * 房颤数据列表
     * </pre>
     *
     * <code>repeated .com.heytap.wearable.health.FcItem data_list = 3;</code>
     */
    java.util.List<oplus.pb.Fc.FcItem> 
        getDataListList();
    /**
     * <pre>
     * 房颤数据列表
     * </pre>
     *
     * <code>repeated .com.heytap.wearable.health.FcItem data_list = 3;</code>
     */
    oplus.pb.Fc.FcItem getDataList(int index);
    /**
     * <pre>
     * 房颤数据列表
     * </pre>
     *
     * <code>repeated .com.heytap.wearable.health.FcItem data_list = 3;</code>
     */
    int getDataListCount();
  }
  /**
   * <pre>
   * 响应数据结构
   * </pre>
   *
   * Protobuf type {@code com.heytap.wearable.health.FcDetailData}
   */
  public  static final class FcDetailData extends
      com.google.protobuf.GeneratedMessageLite<
          FcDetailData, FcDetailData.Builder> implements
      // @@protoc_insertion_point(message_implements:com.heytap.wearable.health.FcDetailData)
      FcDetailDataOrBuilder {
    private FcDetailData() {
      dataList_ = emptyProtobufList();
    }
    public static final int INDEX_FIELD_NUMBER = 1;
    private int index_;
    /**
     * <code>uint32 index = 1;</code>
     * @return The index.
     */
    @java.lang.Override
    public int getIndex() {
      return index_;
    }
    /**
     * <code>uint32 index = 1;</code>
     * @param value The index to set.
     */
    private void setIndex(int value) {
      
      index_ = value;
    }
    /**
     * <code>uint32 index = 1;</code>
     */
    private void clearIndex() {

      index_ = 0;
    }

    public static final int START_TIME_FIELD_NUMBER = 2;
    private int startTime_;
    /**
     * <pre>
     * 第一条数据的开始时间，时间戳（单位秒）
     * </pre>
     *
     * <code>uint32 start_time = 2;</code>
     * @return The startTime.
     */
    @java.lang.Override
    public int getStartTime() {
      return startTime_;
    }
    /**
     * <pre>
     * 第一条数据的开始时间，时间戳（单位秒）
     * </pre>
     *
     * <code>uint32 start_time = 2;</code>
     * @param value The startTime to set.
     */
    private void setStartTime(int value) {
      
      startTime_ = value;
    }
    /**
     * <pre>
     * 第一条数据的开始时间，时间戳（单位秒）
     * </pre>
     *
     * <code>uint32 start_time = 2;</code>
     */
    private void clearStartTime() {

      startTime_ = 0;
    }

    public static final int DATA_LIST_FIELD_NUMBER = 3;
    private com.google.protobuf.Internal.ProtobufList<oplus.pb.Fc.FcItem> dataList_;
    /**
     * <pre>
     * 房颤数据列表
     * </pre>
     *
     * <code>repeated .com.heytap.wearable.health.FcItem data_list = 3;</code>
     */
    @java.lang.Override
    public java.util.List<oplus.pb.Fc.FcItem> getDataListList() {
      return dataList_;
    }
    /**
     * <pre>
     * 房颤数据列表
     * </pre>
     *
     * <code>repeated .com.heytap.wearable.health.FcItem data_list = 3;</code>
     */
    public java.util.List<? extends oplus.pb.Fc.FcItemOrBuilder> 
        getDataListOrBuilderList() {
      return dataList_;
    }
    /**
     * <pre>
     * 房颤数据列表
     * </pre>
     *
     * <code>repeated .com.heytap.wearable.health.FcItem data_list = 3;</code>
     */
    @java.lang.Override
    public int getDataListCount() {
      return dataList_.size();
    }
    /**
     * <pre>
     * 房颤数据列表
     * </pre>
     *
     * <code>repeated .com.heytap.wearable.health.FcItem data_list = 3;</code>
     */
    @java.lang.Override
    public oplus.pb.Fc.FcItem getDataList(int index) {
      return dataList_.get(index);
    }
    /**
     * <pre>
     * 房颤数据列表
     * </pre>
     *
     * <code>repeated .com.heytap.wearable.health.FcItem data_list = 3;</code>
     */
    public oplus.pb.Fc.FcItemOrBuilder getDataListOrBuilder(
        int index) {
      return dataList_.get(index);
    }
    private void ensureDataListIsMutable() {
      com.google.protobuf.Internal.ProtobufList<oplus.pb.Fc.FcItem> tmp = dataList_;
      if (!tmp.isModifiable()) {
        dataList_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <pre>
     * 房颤数据列表
     * </pre>
     *
     * <code>repeated .com.heytap.wearable.health.FcItem data_list = 3;</code>
     */
    private void setDataList(
        int index, oplus.pb.Fc.FcItem value) {
      value.getClass();
  ensureDataListIsMutable();
      dataList_.set(index, value);
    }
    /**
     * <pre>
     * 房颤数据列表
     * </pre>
     *
     * <code>repeated .com.heytap.wearable.health.FcItem data_list = 3;</code>
     */
    private void addDataList(oplus.pb.Fc.FcItem value) {
      value.getClass();
  ensureDataListIsMutable();
      dataList_.add(value);
    }
    /**
     * <pre>
     * 房颤数据列表
     * </pre>
     *
     * <code>repeated .com.heytap.wearable.health.FcItem data_list = 3;</code>
     */
    private void addDataList(
        int index, oplus.pb.Fc.FcItem value) {
      value.getClass();
  ensureDataListIsMutable();
      dataList_.add(index, value);
    }
    /**
     * <pre>
     * 房颤数据列表
     * </pre>
     *
     * <code>repeated .com.heytap.wearable.health.FcItem data_list = 3;</code>
     */
    private void addAllDataList(
        java.lang.Iterable<? extends oplus.pb.Fc.FcItem> values) {
      ensureDataListIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, dataList_);
    }
    /**
     * <pre>
     * 房颤数据列表
     * </pre>
     *
     * <code>repeated .com.heytap.wearable.health.FcItem data_list = 3;</code>
     */
    private void clearDataList() {
      dataList_ = emptyProtobufList();
    }
    /**
     * <pre>
     * 房颤数据列表
     * </pre>
     *
     * <code>repeated .com.heytap.wearable.health.FcItem data_list = 3;</code>
     */
    private void removeDataList(int index) {
      ensureDataListIsMutable();
      dataList_.remove(index);
    }

    public static oplus.pb.Fc.FcDetailData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.Fc.FcDetailData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.Fc.FcDetailData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.Fc.FcDetailData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.Fc.FcDetailData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.Fc.FcDetailData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.Fc.FcDetailData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static oplus.pb.Fc.FcDetailData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static oplus.pb.Fc.FcDetailData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static oplus.pb.Fc.FcDetailData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static oplus.pb.Fc.FcDetailData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static oplus.pb.Fc.FcDetailData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(oplus.pb.Fc.FcDetailData prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * 响应数据结构
     * </pre>
     *
     * Protobuf type {@code com.heytap.wearable.health.FcDetailData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          oplus.pb.Fc.FcDetailData, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.heytap.wearable.health.FcDetailData)
        oplus.pb.Fc.FcDetailDataOrBuilder {
      // Construct using oplus.pb.Fc.FcDetailData.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>uint32 index = 1;</code>
       * @return The index.
       */
      @java.lang.Override
      public int getIndex() {
        return instance.getIndex();
      }
      /**
       * <code>uint32 index = 1;</code>
       * @param value The index to set.
       * @return This builder for chaining.
       */
      public Builder setIndex(int value) {
        copyOnWrite();
        instance.setIndex(value);
        return this;
      }
      /**
       * <code>uint32 index = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIndex() {
        copyOnWrite();
        instance.clearIndex();
        return this;
      }

      /**
       * <pre>
       * 第一条数据的开始时间，时间戳（单位秒）
       * </pre>
       *
       * <code>uint32 start_time = 2;</code>
       * @return The startTime.
       */
      @java.lang.Override
      public int getStartTime() {
        return instance.getStartTime();
      }
      /**
       * <pre>
       * 第一条数据的开始时间，时间戳（单位秒）
       * </pre>
       *
       * <code>uint32 start_time = 2;</code>
       * @param value The startTime to set.
       * @return This builder for chaining.
       */
      public Builder setStartTime(int value) {
        copyOnWrite();
        instance.setStartTime(value);
        return this;
      }
      /**
       * <pre>
       * 第一条数据的开始时间，时间戳（单位秒）
       * </pre>
       *
       * <code>uint32 start_time = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStartTime() {
        copyOnWrite();
        instance.clearStartTime();
        return this;
      }

      /**
       * <pre>
       * 房颤数据列表
       * </pre>
       *
       * <code>repeated .com.heytap.wearable.health.FcItem data_list = 3;</code>
       */
      @java.lang.Override
      public java.util.List<oplus.pb.Fc.FcItem> getDataListList() {
        return java.util.Collections.unmodifiableList(
            instance.getDataListList());
      }
      /**
       * <pre>
       * 房颤数据列表
       * </pre>
       *
       * <code>repeated .com.heytap.wearable.health.FcItem data_list = 3;</code>
       */
      @java.lang.Override
      public int getDataListCount() {
        return instance.getDataListCount();
      }/**
       * <pre>
       * 房颤数据列表
       * </pre>
       *
       * <code>repeated .com.heytap.wearable.health.FcItem data_list = 3;</code>
       */
      @java.lang.Override
      public oplus.pb.Fc.FcItem getDataList(int index) {
        return instance.getDataList(index);
      }
      /**
       * <pre>
       * 房颤数据列表
       * </pre>
       *
       * <code>repeated .com.heytap.wearable.health.FcItem data_list = 3;</code>
       */
      public Builder setDataList(
          int index, oplus.pb.Fc.FcItem value) {
        copyOnWrite();
        instance.setDataList(index, value);
        return this;
      }
      /**
       * <pre>
       * 房颤数据列表
       * </pre>
       *
       * <code>repeated .com.heytap.wearable.health.FcItem data_list = 3;</code>
       */
      public Builder setDataList(
          int index, oplus.pb.Fc.FcItem.Builder builderForValue) {
        copyOnWrite();
        instance.setDataList(index,
            builderForValue.build());
        return this;
      }
      /**
       * <pre>
       * 房颤数据列表
       * </pre>
       *
       * <code>repeated .com.heytap.wearable.health.FcItem data_list = 3;</code>
       */
      public Builder addDataList(oplus.pb.Fc.FcItem value) {
        copyOnWrite();
        instance.addDataList(value);
        return this;
      }
      /**
       * <pre>
       * 房颤数据列表
       * </pre>
       *
       * <code>repeated .com.heytap.wearable.health.FcItem data_list = 3;</code>
       */
      public Builder addDataList(
          int index, oplus.pb.Fc.FcItem value) {
        copyOnWrite();
        instance.addDataList(index, value);
        return this;
      }
      /**
       * <pre>
       * 房颤数据列表
       * </pre>
       *
       * <code>repeated .com.heytap.wearable.health.FcItem data_list = 3;</code>
       */
      public Builder addDataList(
          oplus.pb.Fc.FcItem.Builder builderForValue) {
        copyOnWrite();
        instance.addDataList(builderForValue.build());
        return this;
      }
      /**
       * <pre>
       * 房颤数据列表
       * </pre>
       *
       * <code>repeated .com.heytap.wearable.health.FcItem data_list = 3;</code>
       */
      public Builder addDataList(
          int index, oplus.pb.Fc.FcItem.Builder builderForValue) {
        copyOnWrite();
        instance.addDataList(index,
            builderForValue.build());
        return this;
      }
      /**
       * <pre>
       * 房颤数据列表
       * </pre>
       *
       * <code>repeated .com.heytap.wearable.health.FcItem data_list = 3;</code>
       */
      public Builder addAllDataList(
          java.lang.Iterable<? extends oplus.pb.Fc.FcItem> values) {
        copyOnWrite();
        instance.addAllDataList(values);
        return this;
      }
      /**
       * <pre>
       * 房颤数据列表
       * </pre>
       *
       * <code>repeated .com.heytap.wearable.health.FcItem data_list = 3;</code>
       */
      public Builder clearDataList() {
        copyOnWrite();
        instance.clearDataList();
        return this;
      }
      /**
       * <pre>
       * 房颤数据列表
       * </pre>
       *
       * <code>repeated .com.heytap.wearable.health.FcItem data_list = 3;</code>
       */
      public Builder removeDataList(int index) {
        copyOnWrite();
        instance.removeDataList(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.heytap.wearable.health.FcDetailData)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new oplus.pb.Fc.FcDetailData();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "index_",
              "startTime_",
              "dataList_",
              oplus.pb.Fc.FcItem.class,
            };
            java.lang.String info =
                "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0001\u0000\u0001\u000b\u0002\u000b" +
                "\u0003\u001b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<oplus.pb.Fc.FcDetailData> parser = PARSER;
          if (parser == null) {
            synchronized (oplus.pb.Fc.FcDetailData.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<oplus.pb.Fc.FcDetailData>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.heytap.wearable.health.FcDetailData)
    private static final oplus.pb.Fc.FcDetailData DEFAULT_INSTANCE;
    static {
      FcDetailData defaultInstance = new FcDetailData();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        FcDetailData.class, defaultInstance);
    }

    public static oplus.pb.Fc.FcDetailData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<FcDetailData> PARSER;

    public static com.google.protobuf.Parser<FcDetailData> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface FcItemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.heytap.wearable.health.FcItem)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * 相对于开始时间偏移量（单位：分钟）
     * </pre>
     *
     * <code>uint32 offset = 1;</code>
     * @return The offset.
     */
    int getOffset();

    /**
     * <pre>
     * 是否房颤  0 非房颤  1房颤
     * </pre>
     *
     * <code>uint32 state = 2;</code>
     * @return The state.
     */
    int getState();

    /**
     * <pre>
     * 可信度
     * </pre>
     *
     * <code>uint32 reliability = 3;</code>
     * @return The reliability.
     */
    int getReliability();

    /**
     * <pre>
     * 是否告警 0 正常，1 告警
     * </pre>
     *
     * <code>uint32 type = 4;</code>
     * @return The type.
     */
    int getType();
  }
  /**
   * Protobuf type {@code com.heytap.wearable.health.FcItem}
   */
  public  static final class FcItem extends
      com.google.protobuf.GeneratedMessageLite<
          FcItem, FcItem.Builder> implements
      // @@protoc_insertion_point(message_implements:com.heytap.wearable.health.FcItem)
      FcItemOrBuilder {
    private FcItem() {
    }
    public static final int OFFSET_FIELD_NUMBER = 1;
    private int offset_;
    /**
     * <pre>
     * 相对于开始时间偏移量（单位：分钟）
     * </pre>
     *
     * <code>uint32 offset = 1;</code>
     * @return The offset.
     */
    @java.lang.Override
    public int getOffset() {
      return offset_;
    }
    /**
     * <pre>
     * 相对于开始时间偏移量（单位：分钟）
     * </pre>
     *
     * <code>uint32 offset = 1;</code>
     * @param value The offset to set.
     */
    private void setOffset(int value) {
      
      offset_ = value;
    }
    /**
     * <pre>
     * 相对于开始时间偏移量（单位：分钟）
     * </pre>
     *
     * <code>uint32 offset = 1;</code>
     */
    private void clearOffset() {

      offset_ = 0;
    }

    public static final int STATE_FIELD_NUMBER = 2;
    private int state_;
    /**
     * <pre>
     * 是否房颤  0 非房颤  1房颤
     * </pre>
     *
     * <code>uint32 state = 2;</code>
     * @return The state.
     */
    @java.lang.Override
    public int getState() {
      return state_;
    }
    /**
     * <pre>
     * 是否房颤  0 非房颤  1房颤
     * </pre>
     *
     * <code>uint32 state = 2;</code>
     * @param value The state to set.
     */
    private void setState(int value) {
      
      state_ = value;
    }
    /**
     * <pre>
     * 是否房颤  0 非房颤  1房颤
     * </pre>
     *
     * <code>uint32 state = 2;</code>
     */
    private void clearState() {

      state_ = 0;
    }

    public static final int RELIABILITY_FIELD_NUMBER = 3;
    private int reliability_;
    /**
     * <pre>
     * 可信度
     * </pre>
     *
     * <code>uint32 reliability = 3;</code>
     * @return The reliability.
     */
    @java.lang.Override
    public int getReliability() {
      return reliability_;
    }
    /**
     * <pre>
     * 可信度
     * </pre>
     *
     * <code>uint32 reliability = 3;</code>
     * @param value The reliability to set.
     */
    private void setReliability(int value) {
      
      reliability_ = value;
    }
    /**
     * <pre>
     * 可信度
     * </pre>
     *
     * <code>uint32 reliability = 3;</code>
     */
    private void clearReliability() {

      reliability_ = 0;
    }

    public static final int TYPE_FIELD_NUMBER = 4;
    private int type_;
    /**
     * <pre>
     * 是否告警 0 正常，1 告警
     * </pre>
     *
     * <code>uint32 type = 4;</code>
     * @return The type.
     */
    @java.lang.Override
    public int getType() {
      return type_;
    }
    /**
     * <pre>
     * 是否告警 0 正常，1 告警
     * </pre>
     *
     * <code>uint32 type = 4;</code>
     * @param value The type to set.
     */
    private void setType(int value) {
      
      type_ = value;
    }
    /**
     * <pre>
     * 是否告警 0 正常，1 告警
     * </pre>
     *
     * <code>uint32 type = 4;</code>
     */
    private void clearType() {

      type_ = 0;
    }

    public static oplus.pb.Fc.FcItem parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.Fc.FcItem parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.Fc.FcItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.Fc.FcItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.Fc.FcItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.Fc.FcItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.Fc.FcItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static oplus.pb.Fc.FcItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static oplus.pb.Fc.FcItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static oplus.pb.Fc.FcItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static oplus.pb.Fc.FcItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static oplus.pb.Fc.FcItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(oplus.pb.Fc.FcItem prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code com.heytap.wearable.health.FcItem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          oplus.pb.Fc.FcItem, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.heytap.wearable.health.FcItem)
        oplus.pb.Fc.FcItemOrBuilder {
      // Construct using oplus.pb.Fc.FcItem.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * 相对于开始时间偏移量（单位：分钟）
       * </pre>
       *
       * <code>uint32 offset = 1;</code>
       * @return The offset.
       */
      @java.lang.Override
      public int getOffset() {
        return instance.getOffset();
      }
      /**
       * <pre>
       * 相对于开始时间偏移量（单位：分钟）
       * </pre>
       *
       * <code>uint32 offset = 1;</code>
       * @param value The offset to set.
       * @return This builder for chaining.
       */
      public Builder setOffset(int value) {
        copyOnWrite();
        instance.setOffset(value);
        return this;
      }
      /**
       * <pre>
       * 相对于开始时间偏移量（单位：分钟）
       * </pre>
       *
       * <code>uint32 offset = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOffset() {
        copyOnWrite();
        instance.clearOffset();
        return this;
      }

      /**
       * <pre>
       * 是否房颤  0 非房颤  1房颤
       * </pre>
       *
       * <code>uint32 state = 2;</code>
       * @return The state.
       */
      @java.lang.Override
      public int getState() {
        return instance.getState();
      }
      /**
       * <pre>
       * 是否房颤  0 非房颤  1房颤
       * </pre>
       *
       * <code>uint32 state = 2;</code>
       * @param value The state to set.
       * @return This builder for chaining.
       */
      public Builder setState(int value) {
        copyOnWrite();
        instance.setState(value);
        return this;
      }
      /**
       * <pre>
       * 是否房颤  0 非房颤  1房颤
       * </pre>
       *
       * <code>uint32 state = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearState() {
        copyOnWrite();
        instance.clearState();
        return this;
      }

      /**
       * <pre>
       * 可信度
       * </pre>
       *
       * <code>uint32 reliability = 3;</code>
       * @return The reliability.
       */
      @java.lang.Override
      public int getReliability() {
        return instance.getReliability();
      }
      /**
       * <pre>
       * 可信度
       * </pre>
       *
       * <code>uint32 reliability = 3;</code>
       * @param value The reliability to set.
       * @return This builder for chaining.
       */
      public Builder setReliability(int value) {
        copyOnWrite();
        instance.setReliability(value);
        return this;
      }
      /**
       * <pre>
       * 可信度
       * </pre>
       *
       * <code>uint32 reliability = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearReliability() {
        copyOnWrite();
        instance.clearReliability();
        return this;
      }

      /**
       * <pre>
       * 是否告警 0 正常，1 告警
       * </pre>
       *
       * <code>uint32 type = 4;</code>
       * @return The type.
       */
      @java.lang.Override
      public int getType() {
        return instance.getType();
      }
      /**
       * <pre>
       * 是否告警 0 正常，1 告警
       * </pre>
       *
       * <code>uint32 type = 4;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(int value) {
        copyOnWrite();
        instance.setType(value);
        return this;
      }
      /**
       * <pre>
       * 是否告警 0 正常，1 告警
       * </pre>
       *
       * <code>uint32 type = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        copyOnWrite();
        instance.clearType();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.heytap.wearable.health.FcItem)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new oplus.pb.Fc.FcItem();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "offset_",
              "state_",
              "reliability_",
              "type_",
            };
            java.lang.String info =
                "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0000\u0000\u0001\u000b\u0002\u000b" +
                "\u0003\u000b\u0004\u000b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<oplus.pb.Fc.FcItem> parser = PARSER;
          if (parser == null) {
            synchronized (oplus.pb.Fc.FcItem.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<oplus.pb.Fc.FcItem>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.heytap.wearable.health.FcItem)
    private static final oplus.pb.Fc.FcItem DEFAULT_INSTANCE;
    static {
      FcItem defaultInstance = new FcItem();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        FcItem.class, defaultInstance);
    }

    public static oplus.pb.Fc.FcItem getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<FcItem> PARSER;

    public static com.google.protobuf.Parser<FcItem> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface FcWarnOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.heytap.wearable.health.FcWarn)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>uint32 timestamp = 1;</code>
     * @return The timestamp.
     */
    int getTimestamp();

    /**
     * <pre>
     * 是否房颤  0 非房颤  1房颤
     * </pre>
     *
     * <code>uint32 state = 2;</code>
     * @return The state.
     */
    int getState();

    /**
     * <code>uint32 reliability = 3;</code>
     * @return The reliability.
     */
    int getReliability();
  }
  /**
   * Protobuf type {@code com.heytap.wearable.health.FcWarn}
   */
  public  static final class FcWarn extends
      com.google.protobuf.GeneratedMessageLite<
          FcWarn, FcWarn.Builder> implements
      // @@protoc_insertion_point(message_implements:com.heytap.wearable.health.FcWarn)
      FcWarnOrBuilder {
    private FcWarn() {
    }
    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private int timestamp_;
    /**
     * <code>uint32 timestamp = 1;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public int getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>uint32 timestamp = 1;</code>
     * @param value The timestamp to set.
     */
    private void setTimestamp(int value) {
      
      timestamp_ = value;
    }
    /**
     * <code>uint32 timestamp = 1;</code>
     */
    private void clearTimestamp() {

      timestamp_ = 0;
    }

    public static final int STATE_FIELD_NUMBER = 2;
    private int state_;
    /**
     * <pre>
     * 是否房颤  0 非房颤  1房颤
     * </pre>
     *
     * <code>uint32 state = 2;</code>
     * @return The state.
     */
    @java.lang.Override
    public int getState() {
      return state_;
    }
    /**
     * <pre>
     * 是否房颤  0 非房颤  1房颤
     * </pre>
     *
     * <code>uint32 state = 2;</code>
     * @param value The state to set.
     */
    private void setState(int value) {
      
      state_ = value;
    }
    /**
     * <pre>
     * 是否房颤  0 非房颤  1房颤
     * </pre>
     *
     * <code>uint32 state = 2;</code>
     */
    private void clearState() {

      state_ = 0;
    }

    public static final int RELIABILITY_FIELD_NUMBER = 3;
    private int reliability_;
    /**
     * <code>uint32 reliability = 3;</code>
     * @return The reliability.
     */
    @java.lang.Override
    public int getReliability() {
      return reliability_;
    }
    /**
     * <code>uint32 reliability = 3;</code>
     * @param value The reliability to set.
     */
    private void setReliability(int value) {
      
      reliability_ = value;
    }
    /**
     * <code>uint32 reliability = 3;</code>
     */
    private void clearReliability() {

      reliability_ = 0;
    }

    public static oplus.pb.Fc.FcWarn parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.Fc.FcWarn parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.Fc.FcWarn parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.Fc.FcWarn parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.Fc.FcWarn parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.Fc.FcWarn parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.Fc.FcWarn parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static oplus.pb.Fc.FcWarn parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static oplus.pb.Fc.FcWarn parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static oplus.pb.Fc.FcWarn parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static oplus.pb.Fc.FcWarn parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static oplus.pb.Fc.FcWarn parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(oplus.pb.Fc.FcWarn prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code com.heytap.wearable.health.FcWarn}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          oplus.pb.Fc.FcWarn, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.heytap.wearable.health.FcWarn)
        oplus.pb.Fc.FcWarnOrBuilder {
      // Construct using oplus.pb.Fc.FcWarn.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>uint32 timestamp = 1;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public int getTimestamp() {
        return instance.getTimestamp();
      }
      /**
       * <code>uint32 timestamp = 1;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(int value) {
        copyOnWrite();
        instance.setTimestamp(value);
        return this;
      }
      /**
       * <code>uint32 timestamp = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        copyOnWrite();
        instance.clearTimestamp();
        return this;
      }

      /**
       * <pre>
       * 是否房颤  0 非房颤  1房颤
       * </pre>
       *
       * <code>uint32 state = 2;</code>
       * @return The state.
       */
      @java.lang.Override
      public int getState() {
        return instance.getState();
      }
      /**
       * <pre>
       * 是否房颤  0 非房颤  1房颤
       * </pre>
       *
       * <code>uint32 state = 2;</code>
       * @param value The state to set.
       * @return This builder for chaining.
       */
      public Builder setState(int value) {
        copyOnWrite();
        instance.setState(value);
        return this;
      }
      /**
       * <pre>
       * 是否房颤  0 非房颤  1房颤
       * </pre>
       *
       * <code>uint32 state = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearState() {
        copyOnWrite();
        instance.clearState();
        return this;
      }

      /**
       * <code>uint32 reliability = 3;</code>
       * @return The reliability.
       */
      @java.lang.Override
      public int getReliability() {
        return instance.getReliability();
      }
      /**
       * <code>uint32 reliability = 3;</code>
       * @param value The reliability to set.
       * @return This builder for chaining.
       */
      public Builder setReliability(int value) {
        copyOnWrite();
        instance.setReliability(value);
        return this;
      }
      /**
       * <code>uint32 reliability = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearReliability() {
        copyOnWrite();
        instance.clearReliability();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.heytap.wearable.health.FcWarn)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new oplus.pb.Fc.FcWarn();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "timestamp_",
              "state_",
              "reliability_",
            };
            java.lang.String info =
                "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u000b\u0002\u000b" +
                "\u0003\u000b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<oplus.pb.Fc.FcWarn> parser = PARSER;
          if (parser == null) {
            synchronized (oplus.pb.Fc.FcWarn.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<oplus.pb.Fc.FcWarn>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.heytap.wearable.health.FcWarn)
    private static final oplus.pb.Fc.FcWarn DEFAULT_INSTANCE;
    static {
      FcWarn defaultInstance = new FcWarn();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        FcWarn.class, defaultInstance);
    }

    public static oplus.pb.Fc.FcWarn getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<FcWarn> PARSER;

    public static com.google.protobuf.Parser<FcWarn> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface FcTimestampOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.heytap.wearable.health.FcTimestamp)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>uint32 timestamp = 1;</code>
     * @return The timestamp.
     */
    int getTimestamp();
  }
  /**
   * Protobuf type {@code com.heytap.wearable.health.FcTimestamp}
   */
  public  static final class FcTimestamp extends
      com.google.protobuf.GeneratedMessageLite<
          FcTimestamp, FcTimestamp.Builder> implements
      // @@protoc_insertion_point(message_implements:com.heytap.wearable.health.FcTimestamp)
      FcTimestampOrBuilder {
    private FcTimestamp() {
    }
    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private int timestamp_;
    /**
     * <code>uint32 timestamp = 1;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public int getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>uint32 timestamp = 1;</code>
     * @param value The timestamp to set.
     */
    private void setTimestamp(int value) {
      
      timestamp_ = value;
    }
    /**
     * <code>uint32 timestamp = 1;</code>
     */
    private void clearTimestamp() {

      timestamp_ = 0;
    }

    public static oplus.pb.Fc.FcTimestamp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.Fc.FcTimestamp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.Fc.FcTimestamp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.Fc.FcTimestamp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.Fc.FcTimestamp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.Fc.FcTimestamp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.Fc.FcTimestamp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static oplus.pb.Fc.FcTimestamp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static oplus.pb.Fc.FcTimestamp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static oplus.pb.Fc.FcTimestamp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static oplus.pb.Fc.FcTimestamp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static oplus.pb.Fc.FcTimestamp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(oplus.pb.Fc.FcTimestamp prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code com.heytap.wearable.health.FcTimestamp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          oplus.pb.Fc.FcTimestamp, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.heytap.wearable.health.FcTimestamp)
        oplus.pb.Fc.FcTimestampOrBuilder {
      // Construct using oplus.pb.Fc.FcTimestamp.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>uint32 timestamp = 1;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public int getTimestamp() {
        return instance.getTimestamp();
      }
      /**
       * <code>uint32 timestamp = 1;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(int value) {
        copyOnWrite();
        instance.setTimestamp(value);
        return this;
      }
      /**
       * <code>uint32 timestamp = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        copyOnWrite();
        instance.clearTimestamp();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.heytap.wearable.health.FcTimestamp)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new oplus.pb.Fc.FcTimestamp();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "timestamp_",
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u000b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<oplus.pb.Fc.FcTimestamp> parser = PARSER;
          if (parser == null) {
            synchronized (oplus.pb.Fc.FcTimestamp.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<oplus.pb.Fc.FcTimestamp>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.heytap.wearable.health.FcTimestamp)
    private static final oplus.pb.Fc.FcTimestamp DEFAULT_INSTANCE;
    static {
      FcTimestamp defaultInstance = new FcTimestamp();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        FcTimestamp.class, defaultInstance);
    }

    public static oplus.pb.Fc.FcTimestamp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<FcTimestamp> PARSER;

    public static com.google.protobuf.Parser<FcTimestamp> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
