// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: MinorText.proto
// Protobuf Java Version: 4.28.2

package oplus.pb;

public final class MinorText {
  private MinorText() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface ScienceInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.heytap.wearable.health.ScienceInfo)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated .com.heytap.wearable.health.ScienceInfoItem scienceInfoList = 1;</code>
     */
    java.util.List<oplus.pb.MinorText.ScienceInfoItem> 
        getScienceInfoListList();
    /**
     * <code>repeated .com.heytap.wearable.health.ScienceInfoItem scienceInfoList = 1;</code>
     */
    oplus.pb.MinorText.ScienceInfoItem getScienceInfoList(int index);
    /**
     * <code>repeated .com.heytap.wearable.health.ScienceInfoItem scienceInfoList = 1;</code>
     */
    int getScienceInfoListCount();
  }
  /**
   * Protobuf type {@code com.heytap.wearable.health.ScienceInfo}
   */
  public  static final class ScienceInfo extends
      com.google.protobuf.GeneratedMessageLite<
          ScienceInfo, ScienceInfo.Builder> implements
      // @@protoc_insertion_point(message_implements:com.heytap.wearable.health.ScienceInfo)
      ScienceInfoOrBuilder {
    private ScienceInfo() {
      scienceInfoList_ = emptyProtobufList();
    }
    public static final int SCIENCEINFOLIST_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<oplus.pb.MinorText.ScienceInfoItem> scienceInfoList_;
    /**
     * <code>repeated .com.heytap.wearable.health.ScienceInfoItem scienceInfoList = 1;</code>
     */
    @java.lang.Override
    public java.util.List<oplus.pb.MinorText.ScienceInfoItem> getScienceInfoListList() {
      return scienceInfoList_;
    }
    /**
     * <code>repeated .com.heytap.wearable.health.ScienceInfoItem scienceInfoList = 1;</code>
     */
    public java.util.List<? extends oplus.pb.MinorText.ScienceInfoItemOrBuilder> 
        getScienceInfoListOrBuilderList() {
      return scienceInfoList_;
    }
    /**
     * <code>repeated .com.heytap.wearable.health.ScienceInfoItem scienceInfoList = 1;</code>
     */
    @java.lang.Override
    public int getScienceInfoListCount() {
      return scienceInfoList_.size();
    }
    /**
     * <code>repeated .com.heytap.wearable.health.ScienceInfoItem scienceInfoList = 1;</code>
     */
    @java.lang.Override
    public oplus.pb.MinorText.ScienceInfoItem getScienceInfoList(int index) {
      return scienceInfoList_.get(index);
    }
    /**
     * <code>repeated .com.heytap.wearable.health.ScienceInfoItem scienceInfoList = 1;</code>
     */
    public oplus.pb.MinorText.ScienceInfoItemOrBuilder getScienceInfoListOrBuilder(
        int index) {
      return scienceInfoList_.get(index);
    }
    private void ensureScienceInfoListIsMutable() {
      com.google.protobuf.Internal.ProtobufList<oplus.pb.MinorText.ScienceInfoItem> tmp = scienceInfoList_;
      if (!tmp.isModifiable()) {
        scienceInfoList_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <code>repeated .com.heytap.wearable.health.ScienceInfoItem scienceInfoList = 1;</code>
     */
    private void setScienceInfoList(
        int index, oplus.pb.MinorText.ScienceInfoItem value) {
      value.getClass();
  ensureScienceInfoListIsMutable();
      scienceInfoList_.set(index, value);
    }
    /**
     * <code>repeated .com.heytap.wearable.health.ScienceInfoItem scienceInfoList = 1;</code>
     */
    private void addScienceInfoList(oplus.pb.MinorText.ScienceInfoItem value) {
      value.getClass();
  ensureScienceInfoListIsMutable();
      scienceInfoList_.add(value);
    }
    /**
     * <code>repeated .com.heytap.wearable.health.ScienceInfoItem scienceInfoList = 1;</code>
     */
    private void addScienceInfoList(
        int index, oplus.pb.MinorText.ScienceInfoItem value) {
      value.getClass();
  ensureScienceInfoListIsMutable();
      scienceInfoList_.add(index, value);
    }
    /**
     * <code>repeated .com.heytap.wearable.health.ScienceInfoItem scienceInfoList = 1;</code>
     */
    private void addAllScienceInfoList(
        java.lang.Iterable<? extends oplus.pb.MinorText.ScienceInfoItem> values) {
      ensureScienceInfoListIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, scienceInfoList_);
    }
    /**
     * <code>repeated .com.heytap.wearable.health.ScienceInfoItem scienceInfoList = 1;</code>
     */
    private void clearScienceInfoList() {
      scienceInfoList_ = emptyProtobufList();
    }
    /**
     * <code>repeated .com.heytap.wearable.health.ScienceInfoItem scienceInfoList = 1;</code>
     */
    private void removeScienceInfoList(int index) {
      ensureScienceInfoListIsMutable();
      scienceInfoList_.remove(index);
    }

    public static oplus.pb.MinorText.ScienceInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.MinorText.ScienceInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.MinorText.ScienceInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.MinorText.ScienceInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.MinorText.ScienceInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.MinorText.ScienceInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.MinorText.ScienceInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static oplus.pb.MinorText.ScienceInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static oplus.pb.MinorText.ScienceInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static oplus.pb.MinorText.ScienceInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static oplus.pb.MinorText.ScienceInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static oplus.pb.MinorText.ScienceInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(oplus.pb.MinorText.ScienceInfo prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code com.heytap.wearable.health.ScienceInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          oplus.pb.MinorText.ScienceInfo, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.heytap.wearable.health.ScienceInfo)
        oplus.pb.MinorText.ScienceInfoOrBuilder {
      // Construct using oplus.pb.MinorText.ScienceInfo.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>repeated .com.heytap.wearable.health.ScienceInfoItem scienceInfoList = 1;</code>
       */
      @java.lang.Override
      public java.util.List<oplus.pb.MinorText.ScienceInfoItem> getScienceInfoListList() {
        return java.util.Collections.unmodifiableList(
            instance.getScienceInfoListList());
      }
      /**
       * <code>repeated .com.heytap.wearable.health.ScienceInfoItem scienceInfoList = 1;</code>
       */
      @java.lang.Override
      public int getScienceInfoListCount() {
        return instance.getScienceInfoListCount();
      }/**
       * <code>repeated .com.heytap.wearable.health.ScienceInfoItem scienceInfoList = 1;</code>
       */
      @java.lang.Override
      public oplus.pb.MinorText.ScienceInfoItem getScienceInfoList(int index) {
        return instance.getScienceInfoList(index);
      }
      /**
       * <code>repeated .com.heytap.wearable.health.ScienceInfoItem scienceInfoList = 1;</code>
       */
      public Builder setScienceInfoList(
          int index, oplus.pb.MinorText.ScienceInfoItem value) {
        copyOnWrite();
        instance.setScienceInfoList(index, value);
        return this;
      }
      /**
       * <code>repeated .com.heytap.wearable.health.ScienceInfoItem scienceInfoList = 1;</code>
       */
      public Builder setScienceInfoList(
          int index, oplus.pb.MinorText.ScienceInfoItem.Builder builderForValue) {
        copyOnWrite();
        instance.setScienceInfoList(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.heytap.wearable.health.ScienceInfoItem scienceInfoList = 1;</code>
       */
      public Builder addScienceInfoList(oplus.pb.MinorText.ScienceInfoItem value) {
        copyOnWrite();
        instance.addScienceInfoList(value);
        return this;
      }
      /**
       * <code>repeated .com.heytap.wearable.health.ScienceInfoItem scienceInfoList = 1;</code>
       */
      public Builder addScienceInfoList(
          int index, oplus.pb.MinorText.ScienceInfoItem value) {
        copyOnWrite();
        instance.addScienceInfoList(index, value);
        return this;
      }
      /**
       * <code>repeated .com.heytap.wearable.health.ScienceInfoItem scienceInfoList = 1;</code>
       */
      public Builder addScienceInfoList(
          oplus.pb.MinorText.ScienceInfoItem.Builder builderForValue) {
        copyOnWrite();
        instance.addScienceInfoList(builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.heytap.wearable.health.ScienceInfoItem scienceInfoList = 1;</code>
       */
      public Builder addScienceInfoList(
          int index, oplus.pb.MinorText.ScienceInfoItem.Builder builderForValue) {
        copyOnWrite();
        instance.addScienceInfoList(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.heytap.wearable.health.ScienceInfoItem scienceInfoList = 1;</code>
       */
      public Builder addAllScienceInfoList(
          java.lang.Iterable<? extends oplus.pb.MinorText.ScienceInfoItem> values) {
        copyOnWrite();
        instance.addAllScienceInfoList(values);
        return this;
      }
      /**
       * <code>repeated .com.heytap.wearable.health.ScienceInfoItem scienceInfoList = 1;</code>
       */
      public Builder clearScienceInfoList() {
        copyOnWrite();
        instance.clearScienceInfoList();
        return this;
      }
      /**
       * <code>repeated .com.heytap.wearable.health.ScienceInfoItem scienceInfoList = 1;</code>
       */
      public Builder removeScienceInfoList(int index) {
        copyOnWrite();
        instance.removeScienceInfoList(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.heytap.wearable.health.ScienceInfo)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new oplus.pb.MinorText.ScienceInfo();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "scienceInfoList_",
              oplus.pb.MinorText.ScienceInfoItem.class,
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0001\u0000\u0001\u001b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<oplus.pb.MinorText.ScienceInfo> parser = PARSER;
          if (parser == null) {
            synchronized (oplus.pb.MinorText.ScienceInfo.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<oplus.pb.MinorText.ScienceInfo>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.heytap.wearable.health.ScienceInfo)
    private static final oplus.pb.MinorText.ScienceInfo DEFAULT_INSTANCE;
    static {
      ScienceInfo defaultInstance = new ScienceInfo();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        ScienceInfo.class, defaultInstance);
    }

    public static oplus.pb.MinorText.ScienceInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ScienceInfo> PARSER;

    public static com.google.protobuf.Parser<ScienceInfo> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface ScienceInfoItemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.heytap.wearable.health.ScienceInfoItem)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * 信息类别 1：步数 2：消耗 3：锻炼 4:活动
     * </pre>
     *
     * <code>uint32 infoType = 1;</code>
     * @return The infoType.
     */
    int getInfoType();

    /**
     * <code>repeated .com.heytap.wearable.health.ScienceInfoDetail infoDetailList = 2;</code>
     */
    java.util.List<oplus.pb.MinorText.ScienceInfoDetail> 
        getInfoDetailListList();
    /**
     * <code>repeated .com.heytap.wearable.health.ScienceInfoDetail infoDetailList = 2;</code>
     */
    oplus.pb.MinorText.ScienceInfoDetail getInfoDetailList(int index);
    /**
     * <code>repeated .com.heytap.wearable.health.ScienceInfoDetail infoDetailList = 2;</code>
     */
    int getInfoDetailListCount();
  }
  /**
   * Protobuf type {@code com.heytap.wearable.health.ScienceInfoItem}
   */
  public  static final class ScienceInfoItem extends
      com.google.protobuf.GeneratedMessageLite<
          ScienceInfoItem, ScienceInfoItem.Builder> implements
      // @@protoc_insertion_point(message_implements:com.heytap.wearable.health.ScienceInfoItem)
      ScienceInfoItemOrBuilder {
    private ScienceInfoItem() {
      infoDetailList_ = emptyProtobufList();
    }
    public static final int INFOTYPE_FIELD_NUMBER = 1;
    private int infoType_;
    /**
     * <pre>
     * 信息类别 1：步数 2：消耗 3：锻炼 4:活动
     * </pre>
     *
     * <code>uint32 infoType = 1;</code>
     * @return The infoType.
     */
    @java.lang.Override
    public int getInfoType() {
      return infoType_;
    }
    /**
     * <pre>
     * 信息类别 1：步数 2：消耗 3：锻炼 4:活动
     * </pre>
     *
     * <code>uint32 infoType = 1;</code>
     * @param value The infoType to set.
     */
    private void setInfoType(int value) {
      
      infoType_ = value;
    }
    /**
     * <pre>
     * 信息类别 1：步数 2：消耗 3：锻炼 4:活动
     * </pre>
     *
     * <code>uint32 infoType = 1;</code>
     */
    private void clearInfoType() {

      infoType_ = 0;
    }

    public static final int INFODETAILLIST_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.ProtobufList<oplus.pb.MinorText.ScienceInfoDetail> infoDetailList_;
    /**
     * <code>repeated .com.heytap.wearable.health.ScienceInfoDetail infoDetailList = 2;</code>
     */
    @java.lang.Override
    public java.util.List<oplus.pb.MinorText.ScienceInfoDetail> getInfoDetailListList() {
      return infoDetailList_;
    }
    /**
     * <code>repeated .com.heytap.wearable.health.ScienceInfoDetail infoDetailList = 2;</code>
     */
    public java.util.List<? extends oplus.pb.MinorText.ScienceInfoDetailOrBuilder> 
        getInfoDetailListOrBuilderList() {
      return infoDetailList_;
    }
    /**
     * <code>repeated .com.heytap.wearable.health.ScienceInfoDetail infoDetailList = 2;</code>
     */
    @java.lang.Override
    public int getInfoDetailListCount() {
      return infoDetailList_.size();
    }
    /**
     * <code>repeated .com.heytap.wearable.health.ScienceInfoDetail infoDetailList = 2;</code>
     */
    @java.lang.Override
    public oplus.pb.MinorText.ScienceInfoDetail getInfoDetailList(int index) {
      return infoDetailList_.get(index);
    }
    /**
     * <code>repeated .com.heytap.wearable.health.ScienceInfoDetail infoDetailList = 2;</code>
     */
    public oplus.pb.MinorText.ScienceInfoDetailOrBuilder getInfoDetailListOrBuilder(
        int index) {
      return infoDetailList_.get(index);
    }
    private void ensureInfoDetailListIsMutable() {
      com.google.protobuf.Internal.ProtobufList<oplus.pb.MinorText.ScienceInfoDetail> tmp = infoDetailList_;
      if (!tmp.isModifiable()) {
        infoDetailList_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <code>repeated .com.heytap.wearable.health.ScienceInfoDetail infoDetailList = 2;</code>
     */
    private void setInfoDetailList(
        int index, oplus.pb.MinorText.ScienceInfoDetail value) {
      value.getClass();
  ensureInfoDetailListIsMutable();
      infoDetailList_.set(index, value);
    }
    /**
     * <code>repeated .com.heytap.wearable.health.ScienceInfoDetail infoDetailList = 2;</code>
     */
    private void addInfoDetailList(oplus.pb.MinorText.ScienceInfoDetail value) {
      value.getClass();
  ensureInfoDetailListIsMutable();
      infoDetailList_.add(value);
    }
    /**
     * <code>repeated .com.heytap.wearable.health.ScienceInfoDetail infoDetailList = 2;</code>
     */
    private void addInfoDetailList(
        int index, oplus.pb.MinorText.ScienceInfoDetail value) {
      value.getClass();
  ensureInfoDetailListIsMutable();
      infoDetailList_.add(index, value);
    }
    /**
     * <code>repeated .com.heytap.wearable.health.ScienceInfoDetail infoDetailList = 2;</code>
     */
    private void addAllInfoDetailList(
        java.lang.Iterable<? extends oplus.pb.MinorText.ScienceInfoDetail> values) {
      ensureInfoDetailListIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, infoDetailList_);
    }
    /**
     * <code>repeated .com.heytap.wearable.health.ScienceInfoDetail infoDetailList = 2;</code>
     */
    private void clearInfoDetailList() {
      infoDetailList_ = emptyProtobufList();
    }
    /**
     * <code>repeated .com.heytap.wearable.health.ScienceInfoDetail infoDetailList = 2;</code>
     */
    private void removeInfoDetailList(int index) {
      ensureInfoDetailListIsMutable();
      infoDetailList_.remove(index);
    }

    public static oplus.pb.MinorText.ScienceInfoItem parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.MinorText.ScienceInfoItem parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.MinorText.ScienceInfoItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.MinorText.ScienceInfoItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.MinorText.ScienceInfoItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.MinorText.ScienceInfoItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.MinorText.ScienceInfoItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static oplus.pb.MinorText.ScienceInfoItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static oplus.pb.MinorText.ScienceInfoItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static oplus.pb.MinorText.ScienceInfoItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static oplus.pb.MinorText.ScienceInfoItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static oplus.pb.MinorText.ScienceInfoItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(oplus.pb.MinorText.ScienceInfoItem prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code com.heytap.wearable.health.ScienceInfoItem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          oplus.pb.MinorText.ScienceInfoItem, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.heytap.wearable.health.ScienceInfoItem)
        oplus.pb.MinorText.ScienceInfoItemOrBuilder {
      // Construct using oplus.pb.MinorText.ScienceInfoItem.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * 信息类别 1：步数 2：消耗 3：锻炼 4:活动
       * </pre>
       *
       * <code>uint32 infoType = 1;</code>
       * @return The infoType.
       */
      @java.lang.Override
      public int getInfoType() {
        return instance.getInfoType();
      }
      /**
       * <pre>
       * 信息类别 1：步数 2：消耗 3：锻炼 4:活动
       * </pre>
       *
       * <code>uint32 infoType = 1;</code>
       * @param value The infoType to set.
       * @return This builder for chaining.
       */
      public Builder setInfoType(int value) {
        copyOnWrite();
        instance.setInfoType(value);
        return this;
      }
      /**
       * <pre>
       * 信息类别 1：步数 2：消耗 3：锻炼 4:活动
       * </pre>
       *
       * <code>uint32 infoType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearInfoType() {
        copyOnWrite();
        instance.clearInfoType();
        return this;
      }

      /**
       * <code>repeated .com.heytap.wearable.health.ScienceInfoDetail infoDetailList = 2;</code>
       */
      @java.lang.Override
      public java.util.List<oplus.pb.MinorText.ScienceInfoDetail> getInfoDetailListList() {
        return java.util.Collections.unmodifiableList(
            instance.getInfoDetailListList());
      }
      /**
       * <code>repeated .com.heytap.wearable.health.ScienceInfoDetail infoDetailList = 2;</code>
       */
      @java.lang.Override
      public int getInfoDetailListCount() {
        return instance.getInfoDetailListCount();
      }/**
       * <code>repeated .com.heytap.wearable.health.ScienceInfoDetail infoDetailList = 2;</code>
       */
      @java.lang.Override
      public oplus.pb.MinorText.ScienceInfoDetail getInfoDetailList(int index) {
        return instance.getInfoDetailList(index);
      }
      /**
       * <code>repeated .com.heytap.wearable.health.ScienceInfoDetail infoDetailList = 2;</code>
       */
      public Builder setInfoDetailList(
          int index, oplus.pb.MinorText.ScienceInfoDetail value) {
        copyOnWrite();
        instance.setInfoDetailList(index, value);
        return this;
      }
      /**
       * <code>repeated .com.heytap.wearable.health.ScienceInfoDetail infoDetailList = 2;</code>
       */
      public Builder setInfoDetailList(
          int index, oplus.pb.MinorText.ScienceInfoDetail.Builder builderForValue) {
        copyOnWrite();
        instance.setInfoDetailList(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.heytap.wearable.health.ScienceInfoDetail infoDetailList = 2;</code>
       */
      public Builder addInfoDetailList(oplus.pb.MinorText.ScienceInfoDetail value) {
        copyOnWrite();
        instance.addInfoDetailList(value);
        return this;
      }
      /**
       * <code>repeated .com.heytap.wearable.health.ScienceInfoDetail infoDetailList = 2;</code>
       */
      public Builder addInfoDetailList(
          int index, oplus.pb.MinorText.ScienceInfoDetail value) {
        copyOnWrite();
        instance.addInfoDetailList(index, value);
        return this;
      }
      /**
       * <code>repeated .com.heytap.wearable.health.ScienceInfoDetail infoDetailList = 2;</code>
       */
      public Builder addInfoDetailList(
          oplus.pb.MinorText.ScienceInfoDetail.Builder builderForValue) {
        copyOnWrite();
        instance.addInfoDetailList(builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.heytap.wearable.health.ScienceInfoDetail infoDetailList = 2;</code>
       */
      public Builder addInfoDetailList(
          int index, oplus.pb.MinorText.ScienceInfoDetail.Builder builderForValue) {
        copyOnWrite();
        instance.addInfoDetailList(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.heytap.wearable.health.ScienceInfoDetail infoDetailList = 2;</code>
       */
      public Builder addAllInfoDetailList(
          java.lang.Iterable<? extends oplus.pb.MinorText.ScienceInfoDetail> values) {
        copyOnWrite();
        instance.addAllInfoDetailList(values);
        return this;
      }
      /**
       * <code>repeated .com.heytap.wearable.health.ScienceInfoDetail infoDetailList = 2;</code>
       */
      public Builder clearInfoDetailList() {
        copyOnWrite();
        instance.clearInfoDetailList();
        return this;
      }
      /**
       * <code>repeated .com.heytap.wearable.health.ScienceInfoDetail infoDetailList = 2;</code>
       */
      public Builder removeInfoDetailList(int index) {
        copyOnWrite();
        instance.removeInfoDetailList(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.heytap.wearable.health.ScienceInfoItem)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new oplus.pb.MinorText.ScienceInfoItem();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "infoType_",
              "infoDetailList_",
              oplus.pb.MinorText.ScienceInfoDetail.class,
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0001\u0000\u0001\u000b\u0002\u001b" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<oplus.pb.MinorText.ScienceInfoItem> parser = PARSER;
          if (parser == null) {
            synchronized (oplus.pb.MinorText.ScienceInfoItem.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<oplus.pb.MinorText.ScienceInfoItem>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.heytap.wearable.health.ScienceInfoItem)
    private static final oplus.pb.MinorText.ScienceInfoItem DEFAULT_INSTANCE;
    static {
      ScienceInfoItem defaultInstance = new ScienceInfoItem();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        ScienceInfoItem.class, defaultInstance);
    }

    public static oplus.pb.MinorText.ScienceInfoItem getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ScienceInfoItem> PARSER;

    public static com.google.protobuf.Parser<ScienceInfoItem> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface ScienceInfoDetailOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.heytap.wearable.health.ScienceInfoDetail)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * 序号
     * </pre>
     *
     * <code>uint32 serialNo = 1;</code>
     * @return The serialNo.
     */
    int getSerialNo();

    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string content = 2;</code>
     * @return The content.
     */
    java.lang.String getContent();
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string content = 2;</code>
     * @return The bytes for content.
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <pre>
     * 时间戳（秒）
     * </pre>
     *
     * <code>uint32 modifiedTimestamp = 3;</code>
     * @return The modifiedTimestamp.
     */
    int getModifiedTimestamp();
  }
  /**
   * Protobuf type {@code com.heytap.wearable.health.ScienceInfoDetail}
   */
  public  static final class ScienceInfoDetail extends
      com.google.protobuf.GeneratedMessageLite<
          ScienceInfoDetail, ScienceInfoDetail.Builder> implements
      // @@protoc_insertion_point(message_implements:com.heytap.wearable.health.ScienceInfoDetail)
      ScienceInfoDetailOrBuilder {
    private ScienceInfoDetail() {
      content_ = "";
    }
    public static final int SERIALNO_FIELD_NUMBER = 1;
    private int serialNo_;
    /**
     * <pre>
     * 序号
     * </pre>
     *
     * <code>uint32 serialNo = 1;</code>
     * @return The serialNo.
     */
    @java.lang.Override
    public int getSerialNo() {
      return serialNo_;
    }
    /**
     * <pre>
     * 序号
     * </pre>
     *
     * <code>uint32 serialNo = 1;</code>
     * @param value The serialNo to set.
     */
    private void setSerialNo(int value) {
      
      serialNo_ = value;
    }
    /**
     * <pre>
     * 序号
     * </pre>
     *
     * <code>uint32 serialNo = 1;</code>
     */
    private void clearSerialNo() {

      serialNo_ = 0;
    }

    public static final int CONTENT_FIELD_NUMBER = 2;
    private java.lang.String content_;
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string content = 2;</code>
     * @return The content.
     */
    @java.lang.Override
    public java.lang.String getContent() {
      return content_;
    }
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string content = 2;</code>
     * @return The bytes for content.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getContentBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(content_);
    }
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string content = 2;</code>
     * @param value The content to set.
     */
    private void setContent(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      content_ = value;
    }
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string content = 2;</code>
     */
    private void clearContent() {

      content_ = getDefaultInstance().getContent();
    }
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string content = 2;</code>
     * @param value The bytes for content to set.
     */
    private void setContentBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      content_ = value.toStringUtf8();

    }

    public static final int MODIFIEDTIMESTAMP_FIELD_NUMBER = 3;
    private int modifiedTimestamp_;
    /**
     * <pre>
     * 时间戳（秒）
     * </pre>
     *
     * <code>uint32 modifiedTimestamp = 3;</code>
     * @return The modifiedTimestamp.
     */
    @java.lang.Override
    public int getModifiedTimestamp() {
      return modifiedTimestamp_;
    }
    /**
     * <pre>
     * 时间戳（秒）
     * </pre>
     *
     * <code>uint32 modifiedTimestamp = 3;</code>
     * @param value The modifiedTimestamp to set.
     */
    private void setModifiedTimestamp(int value) {
      
      modifiedTimestamp_ = value;
    }
    /**
     * <pre>
     * 时间戳（秒）
     * </pre>
     *
     * <code>uint32 modifiedTimestamp = 3;</code>
     */
    private void clearModifiedTimestamp() {

      modifiedTimestamp_ = 0;
    }

    public static oplus.pb.MinorText.ScienceInfoDetail parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.MinorText.ScienceInfoDetail parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.MinorText.ScienceInfoDetail parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.MinorText.ScienceInfoDetail parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.MinorText.ScienceInfoDetail parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.MinorText.ScienceInfoDetail parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.MinorText.ScienceInfoDetail parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static oplus.pb.MinorText.ScienceInfoDetail parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static oplus.pb.MinorText.ScienceInfoDetail parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static oplus.pb.MinorText.ScienceInfoDetail parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static oplus.pb.MinorText.ScienceInfoDetail parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static oplus.pb.MinorText.ScienceInfoDetail parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(oplus.pb.MinorText.ScienceInfoDetail prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code com.heytap.wearable.health.ScienceInfoDetail}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          oplus.pb.MinorText.ScienceInfoDetail, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.heytap.wearable.health.ScienceInfoDetail)
        oplus.pb.MinorText.ScienceInfoDetailOrBuilder {
      // Construct using oplus.pb.MinorText.ScienceInfoDetail.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * 序号
       * </pre>
       *
       * <code>uint32 serialNo = 1;</code>
       * @return The serialNo.
       */
      @java.lang.Override
      public int getSerialNo() {
        return instance.getSerialNo();
      }
      /**
       * <pre>
       * 序号
       * </pre>
       *
       * <code>uint32 serialNo = 1;</code>
       * @param value The serialNo to set.
       * @return This builder for chaining.
       */
      public Builder setSerialNo(int value) {
        copyOnWrite();
        instance.setSerialNo(value);
        return this;
      }
      /**
       * <pre>
       * 序号
       * </pre>
       *
       * <code>uint32 serialNo = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSerialNo() {
        copyOnWrite();
        instance.clearSerialNo();
        return this;
      }

      /**
       * <pre>
       * 消息内容
       * </pre>
       *
       * <code>string content = 2;</code>
       * @return The content.
       */
      @java.lang.Override
      public java.lang.String getContent() {
        return instance.getContent();
      }
      /**
       * <pre>
       * 消息内容
       * </pre>
       *
       * <code>string content = 2;</code>
       * @return The bytes for content.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getContentBytes() {
        return instance.getContentBytes();
      }
      /**
       * <pre>
       * 消息内容
       * </pre>
       *
       * <code>string content = 2;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(
          java.lang.String value) {
        copyOnWrite();
        instance.setContent(value);
        return this;
      }
      /**
       * <pre>
       * 消息内容
       * </pre>
       *
       * <code>string content = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        copyOnWrite();
        instance.clearContent();
        return this;
      }
      /**
       * <pre>
       * 消息内容
       * </pre>
       *
       * <code>string content = 2;</code>
       * @param value The bytes for content to set.
       * @return This builder for chaining.
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setContentBytes(value);
        return this;
      }

      /**
       * <pre>
       * 时间戳（秒）
       * </pre>
       *
       * <code>uint32 modifiedTimestamp = 3;</code>
       * @return The modifiedTimestamp.
       */
      @java.lang.Override
      public int getModifiedTimestamp() {
        return instance.getModifiedTimestamp();
      }
      /**
       * <pre>
       * 时间戳（秒）
       * </pre>
       *
       * <code>uint32 modifiedTimestamp = 3;</code>
       * @param value The modifiedTimestamp to set.
       * @return This builder for chaining.
       */
      public Builder setModifiedTimestamp(int value) {
        copyOnWrite();
        instance.setModifiedTimestamp(value);
        return this;
      }
      /**
       * <pre>
       * 时间戳（秒）
       * </pre>
       *
       * <code>uint32 modifiedTimestamp = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearModifiedTimestamp() {
        copyOnWrite();
        instance.clearModifiedTimestamp();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.heytap.wearable.health.ScienceInfoDetail)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new oplus.pb.MinorText.ScienceInfoDetail();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "serialNo_",
              "content_",
              "modifiedTimestamp_",
            };
            java.lang.String info =
                "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u000b\u0002\u0208" +
                "\u0003\u000b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<oplus.pb.MinorText.ScienceInfoDetail> parser = PARSER;
          if (parser == null) {
            synchronized (oplus.pb.MinorText.ScienceInfoDetail.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<oplus.pb.MinorText.ScienceInfoDetail>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.heytap.wearable.health.ScienceInfoDetail)
    private static final oplus.pb.MinorText.ScienceInfoDetail DEFAULT_INSTANCE;
    static {
      ScienceInfoDetail defaultInstance = new ScienceInfoDetail();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        ScienceInfoDetail.class, defaultInstance);
    }

    public static oplus.pb.MinorText.ScienceInfoDetail getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ScienceInfoDetail> PARSER;

    public static com.google.protobuf.Parser<ScienceInfoDetail> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
