// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: PointPressureProto.proto
// Protobuf Java Version: 4.28.2

package oplus.pb;

public final class PointPressureProto {
  private PointPressureProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface PointPressureResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PointPressureProto.PointPressureResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>int32 stress_val = 1;</code>
     * @return The stressVal.
     */
    int getStressVal();

    /**
     * <code>int32 state = 2;</code>
     * @return The state.
     */
    int getState();

    /**
     * <code>int32 reliability = 3;</code>
     * @return The reliability.
     */
    int getReliability();
  }
  /**
   * Protobuf type {@code PointPressureProto.PointPressureResponse}
   */
  public  static final class PointPressureResponse extends
      com.google.protobuf.GeneratedMessageLite<
          PointPressureResponse, PointPressureResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:PointPressureProto.PointPressureResponse)
      PointPressureResponseOrBuilder {
    private PointPressureResponse() {
    }
    public static final int STRESS_VAL_FIELD_NUMBER = 1;
    private int stressVal_;
    /**
     * <code>int32 stress_val = 1;</code>
     * @return The stressVal.
     */
    @java.lang.Override
    public int getStressVal() {
      return stressVal_;
    }
    /**
     * <code>int32 stress_val = 1;</code>
     * @param value The stressVal to set.
     */
    private void setStressVal(int value) {
      
      stressVal_ = value;
    }
    /**
     * <code>int32 stress_val = 1;</code>
     */
    private void clearStressVal() {

      stressVal_ = 0;
    }

    public static final int STATE_FIELD_NUMBER = 2;
    private int state_;
    /**
     * <code>int32 state = 2;</code>
     * @return The state.
     */
    @java.lang.Override
    public int getState() {
      return state_;
    }
    /**
     * <code>int32 state = 2;</code>
     * @param value The state to set.
     */
    private void setState(int value) {
      
      state_ = value;
    }
    /**
     * <code>int32 state = 2;</code>
     */
    private void clearState() {

      state_ = 0;
    }

    public static final int RELIABILITY_FIELD_NUMBER = 3;
    private int reliability_;
    /**
     * <code>int32 reliability = 3;</code>
     * @return The reliability.
     */
    @java.lang.Override
    public int getReliability() {
      return reliability_;
    }
    /**
     * <code>int32 reliability = 3;</code>
     * @param value The reliability to set.
     */
    private void setReliability(int value) {
      
      reliability_ = value;
    }
    /**
     * <code>int32 reliability = 3;</code>
     */
    private void clearReliability() {

      reliability_ = 0;
    }

    public static oplus.pb.PointPressureProto.PointPressureResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.PointPressureProto.PointPressureResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.PointPressureProto.PointPressureResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.PointPressureProto.PointPressureResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.PointPressureProto.PointPressureResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.PointPressureProto.PointPressureResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.PointPressureProto.PointPressureResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static oplus.pb.PointPressureProto.PointPressureResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static oplus.pb.PointPressureProto.PointPressureResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static oplus.pb.PointPressureProto.PointPressureResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static oplus.pb.PointPressureProto.PointPressureResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static oplus.pb.PointPressureProto.PointPressureResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(oplus.pb.PointPressureProto.PointPressureResponse prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code PointPressureProto.PointPressureResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          oplus.pb.PointPressureProto.PointPressureResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:PointPressureProto.PointPressureResponse)
        oplus.pb.PointPressureProto.PointPressureResponseOrBuilder {
      // Construct using oplus.pb.PointPressureProto.PointPressureResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>int32 stress_val = 1;</code>
       * @return The stressVal.
       */
      @java.lang.Override
      public int getStressVal() {
        return instance.getStressVal();
      }
      /**
       * <code>int32 stress_val = 1;</code>
       * @param value The stressVal to set.
       * @return This builder for chaining.
       */
      public Builder setStressVal(int value) {
        copyOnWrite();
        instance.setStressVal(value);
        return this;
      }
      /**
       * <code>int32 stress_val = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStressVal() {
        copyOnWrite();
        instance.clearStressVal();
        return this;
      }

      /**
       * <code>int32 state = 2;</code>
       * @return The state.
       */
      @java.lang.Override
      public int getState() {
        return instance.getState();
      }
      /**
       * <code>int32 state = 2;</code>
       * @param value The state to set.
       * @return This builder for chaining.
       */
      public Builder setState(int value) {
        copyOnWrite();
        instance.setState(value);
        return this;
      }
      /**
       * <code>int32 state = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearState() {
        copyOnWrite();
        instance.clearState();
        return this;
      }

      /**
       * <code>int32 reliability = 3;</code>
       * @return The reliability.
       */
      @java.lang.Override
      public int getReliability() {
        return instance.getReliability();
      }
      /**
       * <code>int32 reliability = 3;</code>
       * @param value The reliability to set.
       * @return This builder for chaining.
       */
      public Builder setReliability(int value) {
        copyOnWrite();
        instance.setReliability(value);
        return this;
      }
      /**
       * <code>int32 reliability = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearReliability() {
        copyOnWrite();
        instance.clearReliability();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PointPressureProto.PointPressureResponse)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new oplus.pb.PointPressureProto.PointPressureResponse();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "stressVal_",
              "state_",
              "reliability_",
            };
            java.lang.String info =
                "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0004\u0002\u0004" +
                "\u0003\u0004";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<oplus.pb.PointPressureProto.PointPressureResponse> parser = PARSER;
          if (parser == null) {
            synchronized (oplus.pb.PointPressureProto.PointPressureResponse.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<oplus.pb.PointPressureProto.PointPressureResponse>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:PointPressureProto.PointPressureResponse)
    private static final oplus.pb.PointPressureProto.PointPressureResponse DEFAULT_INSTANCE;
    static {
      PointPressureResponse defaultInstance = new PointPressureResponse();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        PointPressureResponse.class, defaultInstance);
    }

    public static oplus.pb.PointPressureProto.PointPressureResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<PointPressureResponse> PARSER;

    public static com.google.protobuf.Parser<PointPressureResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface PressureRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PointPressureProto.PressureRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>int32 sw = 1;</code>
     * @return The sw.
     */
    int getSw();

    /**
     * <code>int32 interval = 2;</code>
     * @return The interval.
     */
    int getInterval();
  }
  /**
   * Protobuf type {@code PointPressureProto.PressureRequest}
   */
  public  static final class PressureRequest extends
      com.google.protobuf.GeneratedMessageLite<
          PressureRequest, PressureRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:PointPressureProto.PressureRequest)
      PressureRequestOrBuilder {
    private PressureRequest() {
    }
    public static final int SW_FIELD_NUMBER = 1;
    private int sw_;
    /**
     * <code>int32 sw = 1;</code>
     * @return The sw.
     */
    @java.lang.Override
    public int getSw() {
      return sw_;
    }
    /**
     * <code>int32 sw = 1;</code>
     * @param value The sw to set.
     */
    private void setSw(int value) {
      
      sw_ = value;
    }
    /**
     * <code>int32 sw = 1;</code>
     */
    private void clearSw() {

      sw_ = 0;
    }

    public static final int INTERVAL_FIELD_NUMBER = 2;
    private int interval_;
    /**
     * <code>int32 interval = 2;</code>
     * @return The interval.
     */
    @java.lang.Override
    public int getInterval() {
      return interval_;
    }
    /**
     * <code>int32 interval = 2;</code>
     * @param value The interval to set.
     */
    private void setInterval(int value) {
      
      interval_ = value;
    }
    /**
     * <code>int32 interval = 2;</code>
     */
    private void clearInterval() {

      interval_ = 0;
    }

    public static oplus.pb.PointPressureProto.PressureRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.PointPressureProto.PressureRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.PointPressureProto.PressureRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.PointPressureProto.PressureRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.PointPressureProto.PressureRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.PointPressureProto.PressureRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.PointPressureProto.PressureRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static oplus.pb.PointPressureProto.PressureRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static oplus.pb.PointPressureProto.PressureRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static oplus.pb.PointPressureProto.PressureRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static oplus.pb.PointPressureProto.PressureRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static oplus.pb.PointPressureProto.PressureRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(oplus.pb.PointPressureProto.PressureRequest prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code PointPressureProto.PressureRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          oplus.pb.PointPressureProto.PressureRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:PointPressureProto.PressureRequest)
        oplus.pb.PointPressureProto.PressureRequestOrBuilder {
      // Construct using oplus.pb.PointPressureProto.PressureRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>int32 sw = 1;</code>
       * @return The sw.
       */
      @java.lang.Override
      public int getSw() {
        return instance.getSw();
      }
      /**
       * <code>int32 sw = 1;</code>
       * @param value The sw to set.
       * @return This builder for chaining.
       */
      public Builder setSw(int value) {
        copyOnWrite();
        instance.setSw(value);
        return this;
      }
      /**
       * <code>int32 sw = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSw() {
        copyOnWrite();
        instance.clearSw();
        return this;
      }

      /**
       * <code>int32 interval = 2;</code>
       * @return The interval.
       */
      @java.lang.Override
      public int getInterval() {
        return instance.getInterval();
      }
      /**
       * <code>int32 interval = 2;</code>
       * @param value The interval to set.
       * @return This builder for chaining.
       */
      public Builder setInterval(int value) {
        copyOnWrite();
        instance.setInterval(value);
        return this;
      }
      /**
       * <code>int32 interval = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearInterval() {
        copyOnWrite();
        instance.clearInterval();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PointPressureProto.PressureRequest)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new oplus.pb.PointPressureProto.PressureRequest();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "sw_",
              "interval_",
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0004\u0002\u0004" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<oplus.pb.PointPressureProto.PressureRequest> parser = PARSER;
          if (parser == null) {
            synchronized (oplus.pb.PointPressureProto.PressureRequest.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<oplus.pb.PointPressureProto.PressureRequest>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:PointPressureProto.PressureRequest)
    private static final oplus.pb.PointPressureProto.PressureRequest DEFAULT_INSTANCE;
    static {
      PressureRequest defaultInstance = new PressureRequest();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        PressureRequest.class, defaultInstance);
    }

    public static oplus.pb.PointPressureProto.PressureRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<PressureRequest> PARSER;

    public static com.google.protobuf.Parser<PressureRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
