// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: SystemTime.proto
// Protobuf Java Version: 4.28.2

package oplus.pb;

public final class SystemTime {
  private SystemTime() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface req_update_gmt_time_tOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SystemTime.req_update_gmt_time_t)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>uint32 time = 1;</code>
     * @return The time.
     */
    int getTime();

    /**
     * <code>uint32 oldTime = 2;</code>
     * @return The oldTime.
     */
    int getOldTime();
  }
  /**
   * Protobuf type {@code SystemTime.req_update_gmt_time_t}
   */
  public  static final class req_update_gmt_time_t extends
      com.google.protobuf.GeneratedMessageLite<
          req_update_gmt_time_t, req_update_gmt_time_t.Builder> implements
      // @@protoc_insertion_point(message_implements:SystemTime.req_update_gmt_time_t)
      req_update_gmt_time_tOrBuilder {
    private req_update_gmt_time_t() {
    }
    public static final int TIME_FIELD_NUMBER = 1;
    private int time_;
    /**
     * <code>uint32 time = 1;</code>
     * @return The time.
     */
    @java.lang.Override
    public int getTime() {
      return time_;
    }
    /**
     * <code>uint32 time = 1;</code>
     * @param value The time to set.
     */
    private void setTime(int value) {
      
      time_ = value;
    }
    /**
     * <code>uint32 time = 1;</code>
     */
    private void clearTime() {

      time_ = 0;
    }

    public static final int OLDTIME_FIELD_NUMBER = 2;
    private int oldTime_;
    /**
     * <code>uint32 oldTime = 2;</code>
     * @return The oldTime.
     */
    @java.lang.Override
    public int getOldTime() {
      return oldTime_;
    }
    /**
     * <code>uint32 oldTime = 2;</code>
     * @param value The oldTime to set.
     */
    private void setOldTime(int value) {
      
      oldTime_ = value;
    }
    /**
     * <code>uint32 oldTime = 2;</code>
     */
    private void clearOldTime() {

      oldTime_ = 0;
    }

    public static oplus.pb.SystemTime.req_update_gmt_time_t parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.SystemTime.req_update_gmt_time_t parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.SystemTime.req_update_gmt_time_t parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.SystemTime.req_update_gmt_time_t parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.SystemTime.req_update_gmt_time_t parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.SystemTime.req_update_gmt_time_t parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.SystemTime.req_update_gmt_time_t parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static oplus.pb.SystemTime.req_update_gmt_time_t parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static oplus.pb.SystemTime.req_update_gmt_time_t parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static oplus.pb.SystemTime.req_update_gmt_time_t parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static oplus.pb.SystemTime.req_update_gmt_time_t parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static oplus.pb.SystemTime.req_update_gmt_time_t parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(oplus.pb.SystemTime.req_update_gmt_time_t prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code SystemTime.req_update_gmt_time_t}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          oplus.pb.SystemTime.req_update_gmt_time_t, Builder> implements
        // @@protoc_insertion_point(builder_implements:SystemTime.req_update_gmt_time_t)
        oplus.pb.SystemTime.req_update_gmt_time_tOrBuilder {
      // Construct using oplus.pb.SystemTime.req_update_gmt_time_t.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>uint32 time = 1;</code>
       * @return The time.
       */
      @java.lang.Override
      public int getTime() {
        return instance.getTime();
      }
      /**
       * <code>uint32 time = 1;</code>
       * @param value The time to set.
       * @return This builder for chaining.
       */
      public Builder setTime(int value) {
        copyOnWrite();
        instance.setTime(value);
        return this;
      }
      /**
       * <code>uint32 time = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTime() {
        copyOnWrite();
        instance.clearTime();
        return this;
      }

      /**
       * <code>uint32 oldTime = 2;</code>
       * @return The oldTime.
       */
      @java.lang.Override
      public int getOldTime() {
        return instance.getOldTime();
      }
      /**
       * <code>uint32 oldTime = 2;</code>
       * @param value The oldTime to set.
       * @return This builder for chaining.
       */
      public Builder setOldTime(int value) {
        copyOnWrite();
        instance.setOldTime(value);
        return this;
      }
      /**
       * <code>uint32 oldTime = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearOldTime() {
        copyOnWrite();
        instance.clearOldTime();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:SystemTime.req_update_gmt_time_t)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new oplus.pb.SystemTime.req_update_gmt_time_t();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "time_",
              "oldTime_",
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u000b\u0002\u000b" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<oplus.pb.SystemTime.req_update_gmt_time_t> parser = PARSER;
          if (parser == null) {
            synchronized (oplus.pb.SystemTime.req_update_gmt_time_t.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<oplus.pb.SystemTime.req_update_gmt_time_t>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:SystemTime.req_update_gmt_time_t)
    private static final oplus.pb.SystemTime.req_update_gmt_time_t DEFAULT_INSTANCE;
    static {
      req_update_gmt_time_t defaultInstance = new req_update_gmt_time_t();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        req_update_gmt_time_t.class, defaultInstance);
    }

    public static oplus.pb.SystemTime.req_update_gmt_time_t getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<req_update_gmt_time_t> PARSER;

    public static com.google.protobuf.Parser<req_update_gmt_time_t> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface req_update_sys_time_tOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SystemTime.req_update_sys_time_t)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>uint32 time = 1;</code>
     * @return The time.
     */
    int getTime();

    /**
     * <code>uint32 oldTime = 2;</code>
     * @return The oldTime.
     */
    int getOldTime();

    /**
     * <code>sint32 timezone = 3;</code>
     * @return The timezone.
     */
    int getTimezone();

    /**
     * <code>sint32 oldTimezone = 4;</code>
     * @return The oldTimezone.
     */
    int getOldTimezone();

    /**
     * <code>uint32 type = 5;</code>
     * @return The type.
     */
    int getType();
  }
  /**
   * Protobuf type {@code SystemTime.req_update_sys_time_t}
   */
  public  static final class req_update_sys_time_t extends
      com.google.protobuf.GeneratedMessageLite<
          req_update_sys_time_t, req_update_sys_time_t.Builder> implements
      // @@protoc_insertion_point(message_implements:SystemTime.req_update_sys_time_t)
      req_update_sys_time_tOrBuilder {
    private req_update_sys_time_t() {
    }
    public static final int TIME_FIELD_NUMBER = 1;
    private int time_;
    /**
     * <code>uint32 time = 1;</code>
     * @return The time.
     */
    @java.lang.Override
    public int getTime() {
      return time_;
    }
    /**
     * <code>uint32 time = 1;</code>
     * @param value The time to set.
     */
    private void setTime(int value) {
      
      time_ = value;
    }
    /**
     * <code>uint32 time = 1;</code>
     */
    private void clearTime() {

      time_ = 0;
    }

    public static final int OLDTIME_FIELD_NUMBER = 2;
    private int oldTime_;
    /**
     * <code>uint32 oldTime = 2;</code>
     * @return The oldTime.
     */
    @java.lang.Override
    public int getOldTime() {
      return oldTime_;
    }
    /**
     * <code>uint32 oldTime = 2;</code>
     * @param value The oldTime to set.
     */
    private void setOldTime(int value) {
      
      oldTime_ = value;
    }
    /**
     * <code>uint32 oldTime = 2;</code>
     */
    private void clearOldTime() {

      oldTime_ = 0;
    }

    public static final int TIMEZONE_FIELD_NUMBER = 3;
    private int timezone_;
    /**
     * <code>sint32 timezone = 3;</code>
     * @return The timezone.
     */
    @java.lang.Override
    public int getTimezone() {
      return timezone_;
    }
    /**
     * <code>sint32 timezone = 3;</code>
     * @param value The timezone to set.
     */
    private void setTimezone(int value) {
      
      timezone_ = value;
    }
    /**
     * <code>sint32 timezone = 3;</code>
     */
    private void clearTimezone() {

      timezone_ = 0;
    }

    public static final int OLDTIMEZONE_FIELD_NUMBER = 4;
    private int oldTimezone_;
    /**
     * <code>sint32 oldTimezone = 4;</code>
     * @return The oldTimezone.
     */
    @java.lang.Override
    public int getOldTimezone() {
      return oldTimezone_;
    }
    /**
     * <code>sint32 oldTimezone = 4;</code>
     * @param value The oldTimezone to set.
     */
    private void setOldTimezone(int value) {
      
      oldTimezone_ = value;
    }
    /**
     * <code>sint32 oldTimezone = 4;</code>
     */
    private void clearOldTimezone() {

      oldTimezone_ = 0;
    }

    public static final int TYPE_FIELD_NUMBER = 5;
    private int type_;
    /**
     * <code>uint32 type = 5;</code>
     * @return The type.
     */
    @java.lang.Override
    public int getType() {
      return type_;
    }
    /**
     * <code>uint32 type = 5;</code>
     * @param value The type to set.
     */
    private void setType(int value) {
      
      type_ = value;
    }
    /**
     * <code>uint32 type = 5;</code>
     */
    private void clearType() {

      type_ = 0;
    }

    public static oplus.pb.SystemTime.req_update_sys_time_t parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.SystemTime.req_update_sys_time_t parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.SystemTime.req_update_sys_time_t parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.SystemTime.req_update_sys_time_t parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.SystemTime.req_update_sys_time_t parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.SystemTime.req_update_sys_time_t parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.SystemTime.req_update_sys_time_t parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static oplus.pb.SystemTime.req_update_sys_time_t parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static oplus.pb.SystemTime.req_update_sys_time_t parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static oplus.pb.SystemTime.req_update_sys_time_t parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static oplus.pb.SystemTime.req_update_sys_time_t parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static oplus.pb.SystemTime.req_update_sys_time_t parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(oplus.pb.SystemTime.req_update_sys_time_t prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code SystemTime.req_update_sys_time_t}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          oplus.pb.SystemTime.req_update_sys_time_t, Builder> implements
        // @@protoc_insertion_point(builder_implements:SystemTime.req_update_sys_time_t)
        oplus.pb.SystemTime.req_update_sys_time_tOrBuilder {
      // Construct using oplus.pb.SystemTime.req_update_sys_time_t.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>uint32 time = 1;</code>
       * @return The time.
       */
      @java.lang.Override
      public int getTime() {
        return instance.getTime();
      }
      /**
       * <code>uint32 time = 1;</code>
       * @param value The time to set.
       * @return This builder for chaining.
       */
      public Builder setTime(int value) {
        copyOnWrite();
        instance.setTime(value);
        return this;
      }
      /**
       * <code>uint32 time = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTime() {
        copyOnWrite();
        instance.clearTime();
        return this;
      }

      /**
       * <code>uint32 oldTime = 2;</code>
       * @return The oldTime.
       */
      @java.lang.Override
      public int getOldTime() {
        return instance.getOldTime();
      }
      /**
       * <code>uint32 oldTime = 2;</code>
       * @param value The oldTime to set.
       * @return This builder for chaining.
       */
      public Builder setOldTime(int value) {
        copyOnWrite();
        instance.setOldTime(value);
        return this;
      }
      /**
       * <code>uint32 oldTime = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearOldTime() {
        copyOnWrite();
        instance.clearOldTime();
        return this;
      }

      /**
       * <code>sint32 timezone = 3;</code>
       * @return The timezone.
       */
      @java.lang.Override
      public int getTimezone() {
        return instance.getTimezone();
      }
      /**
       * <code>sint32 timezone = 3;</code>
       * @param value The timezone to set.
       * @return This builder for chaining.
       */
      public Builder setTimezone(int value) {
        copyOnWrite();
        instance.setTimezone(value);
        return this;
      }
      /**
       * <code>sint32 timezone = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimezone() {
        copyOnWrite();
        instance.clearTimezone();
        return this;
      }

      /**
       * <code>sint32 oldTimezone = 4;</code>
       * @return The oldTimezone.
       */
      @java.lang.Override
      public int getOldTimezone() {
        return instance.getOldTimezone();
      }
      /**
       * <code>sint32 oldTimezone = 4;</code>
       * @param value The oldTimezone to set.
       * @return This builder for chaining.
       */
      public Builder setOldTimezone(int value) {
        copyOnWrite();
        instance.setOldTimezone(value);
        return this;
      }
      /**
       * <code>sint32 oldTimezone = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearOldTimezone() {
        copyOnWrite();
        instance.clearOldTimezone();
        return this;
      }

      /**
       * <code>uint32 type = 5;</code>
       * @return The type.
       */
      @java.lang.Override
      public int getType() {
        return instance.getType();
      }
      /**
       * <code>uint32 type = 5;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(int value) {
        copyOnWrite();
        instance.setType(value);
        return this;
      }
      /**
       * <code>uint32 type = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        copyOnWrite();
        instance.clearType();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:SystemTime.req_update_sys_time_t)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new oplus.pb.SystemTime.req_update_sys_time_t();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "time_",
              "oldTime_",
              "timezone_",
              "oldTimezone_",
              "type_",
            };
            java.lang.String info =
                "\u0000\u0005\u0000\u0000\u0001\u0005\u0005\u0000\u0000\u0000\u0001\u000b\u0002\u000b" +
                "\u0003\u000f\u0004\u000f\u0005\u000b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<oplus.pb.SystemTime.req_update_sys_time_t> parser = PARSER;
          if (parser == null) {
            synchronized (oplus.pb.SystemTime.req_update_sys_time_t.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<oplus.pb.SystemTime.req_update_sys_time_t>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:SystemTime.req_update_sys_time_t)
    private static final oplus.pb.SystemTime.req_update_sys_time_t DEFAULT_INSTANCE;
    static {
      req_update_sys_time_t defaultInstance = new req_update_sys_time_t();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        req_update_sys_time_t.class, defaultInstance);
    }

    public static oplus.pb.SystemTime.req_update_sys_time_t getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<req_update_sys_time_t> PARSER;

    public static com.google.protobuf.Parser<req_update_sys_time_t> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface req_read_sys_time_tOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SystemTime.req_read_sys_time_t)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>uint32 type = 1;</code>
     * @return The type.
     */
    int getType();
  }
  /**
   * Protobuf type {@code SystemTime.req_read_sys_time_t}
   */
  public  static final class req_read_sys_time_t extends
      com.google.protobuf.GeneratedMessageLite<
          req_read_sys_time_t, req_read_sys_time_t.Builder> implements
      // @@protoc_insertion_point(message_implements:SystemTime.req_read_sys_time_t)
      req_read_sys_time_tOrBuilder {
    private req_read_sys_time_t() {
    }
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>uint32 type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public int getType() {
      return type_;
    }
    /**
     * <code>uint32 type = 1;</code>
     * @param value The type to set.
     */
    private void setType(int value) {
      
      type_ = value;
    }
    /**
     * <code>uint32 type = 1;</code>
     */
    private void clearType() {

      type_ = 0;
    }

    public static oplus.pb.SystemTime.req_read_sys_time_t parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.SystemTime.req_read_sys_time_t parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.SystemTime.req_read_sys_time_t parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.SystemTime.req_read_sys_time_t parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.SystemTime.req_read_sys_time_t parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.SystemTime.req_read_sys_time_t parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.SystemTime.req_read_sys_time_t parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static oplus.pb.SystemTime.req_read_sys_time_t parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static oplus.pb.SystemTime.req_read_sys_time_t parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static oplus.pb.SystemTime.req_read_sys_time_t parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static oplus.pb.SystemTime.req_read_sys_time_t parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static oplus.pb.SystemTime.req_read_sys_time_t parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(oplus.pb.SystemTime.req_read_sys_time_t prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code SystemTime.req_read_sys_time_t}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          oplus.pb.SystemTime.req_read_sys_time_t, Builder> implements
        // @@protoc_insertion_point(builder_implements:SystemTime.req_read_sys_time_t)
        oplus.pb.SystemTime.req_read_sys_time_tOrBuilder {
      // Construct using oplus.pb.SystemTime.req_read_sys_time_t.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>uint32 type = 1;</code>
       * @return The type.
       */
      @java.lang.Override
      public int getType() {
        return instance.getType();
      }
      /**
       * <code>uint32 type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(int value) {
        copyOnWrite();
        instance.setType(value);
        return this;
      }
      /**
       * <code>uint32 type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        copyOnWrite();
        instance.clearType();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:SystemTime.req_read_sys_time_t)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new oplus.pb.SystemTime.req_read_sys_time_t();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "type_",
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u000b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<oplus.pb.SystemTime.req_read_sys_time_t> parser = PARSER;
          if (parser == null) {
            synchronized (oplus.pb.SystemTime.req_read_sys_time_t.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<oplus.pb.SystemTime.req_read_sys_time_t>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:SystemTime.req_read_sys_time_t)
    private static final oplus.pb.SystemTime.req_read_sys_time_t DEFAULT_INSTANCE;
    static {
      req_read_sys_time_t defaultInstance = new req_read_sys_time_t();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        req_read_sys_time_t.class, defaultInstance);
    }

    public static oplus.pb.SystemTime.req_read_sys_time_t getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<req_read_sys_time_t> PARSER;

    public static com.google.protobuf.Parser<req_read_sys_time_t> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface rsp_update_gmt_time_tOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SystemTime.rsp_update_gmt_time_t)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>uint32 type = 1;</code>
     * @return The type.
     */
    int getType();

    /**
     * <code>uint32 time = 2;</code>
     * @return The time.
     */
    int getTime();

    /**
     * <code>uint32 oldTime = 3;</code>
     * @return The oldTime.
     */
    int getOldTime();
  }
  /**
   * Protobuf type {@code SystemTime.rsp_update_gmt_time_t}
   */
  public  static final class rsp_update_gmt_time_t extends
      com.google.protobuf.GeneratedMessageLite<
          rsp_update_gmt_time_t, rsp_update_gmt_time_t.Builder> implements
      // @@protoc_insertion_point(message_implements:SystemTime.rsp_update_gmt_time_t)
      rsp_update_gmt_time_tOrBuilder {
    private rsp_update_gmt_time_t() {
    }
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>uint32 type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public int getType() {
      return type_;
    }
    /**
     * <code>uint32 type = 1;</code>
     * @param value The type to set.
     */
    private void setType(int value) {
      
      type_ = value;
    }
    /**
     * <code>uint32 type = 1;</code>
     */
    private void clearType() {

      type_ = 0;
    }

    public static final int TIME_FIELD_NUMBER = 2;
    private int time_;
    /**
     * <code>uint32 time = 2;</code>
     * @return The time.
     */
    @java.lang.Override
    public int getTime() {
      return time_;
    }
    /**
     * <code>uint32 time = 2;</code>
     * @param value The time to set.
     */
    private void setTime(int value) {
      
      time_ = value;
    }
    /**
     * <code>uint32 time = 2;</code>
     */
    private void clearTime() {

      time_ = 0;
    }

    public static final int OLDTIME_FIELD_NUMBER = 3;
    private int oldTime_;
    /**
     * <code>uint32 oldTime = 3;</code>
     * @return The oldTime.
     */
    @java.lang.Override
    public int getOldTime() {
      return oldTime_;
    }
    /**
     * <code>uint32 oldTime = 3;</code>
     * @param value The oldTime to set.
     */
    private void setOldTime(int value) {
      
      oldTime_ = value;
    }
    /**
     * <code>uint32 oldTime = 3;</code>
     */
    private void clearOldTime() {

      oldTime_ = 0;
    }

    public static oplus.pb.SystemTime.rsp_update_gmt_time_t parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.SystemTime.rsp_update_gmt_time_t parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.SystemTime.rsp_update_gmt_time_t parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.SystemTime.rsp_update_gmt_time_t parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.SystemTime.rsp_update_gmt_time_t parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.SystemTime.rsp_update_gmt_time_t parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.SystemTime.rsp_update_gmt_time_t parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static oplus.pb.SystemTime.rsp_update_gmt_time_t parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static oplus.pb.SystemTime.rsp_update_gmt_time_t parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static oplus.pb.SystemTime.rsp_update_gmt_time_t parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static oplus.pb.SystemTime.rsp_update_gmt_time_t parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static oplus.pb.SystemTime.rsp_update_gmt_time_t parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(oplus.pb.SystemTime.rsp_update_gmt_time_t prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code SystemTime.rsp_update_gmt_time_t}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          oplus.pb.SystemTime.rsp_update_gmt_time_t, Builder> implements
        // @@protoc_insertion_point(builder_implements:SystemTime.rsp_update_gmt_time_t)
        oplus.pb.SystemTime.rsp_update_gmt_time_tOrBuilder {
      // Construct using oplus.pb.SystemTime.rsp_update_gmt_time_t.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>uint32 type = 1;</code>
       * @return The type.
       */
      @java.lang.Override
      public int getType() {
        return instance.getType();
      }
      /**
       * <code>uint32 type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(int value) {
        copyOnWrite();
        instance.setType(value);
        return this;
      }
      /**
       * <code>uint32 type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        copyOnWrite();
        instance.clearType();
        return this;
      }

      /**
       * <code>uint32 time = 2;</code>
       * @return The time.
       */
      @java.lang.Override
      public int getTime() {
        return instance.getTime();
      }
      /**
       * <code>uint32 time = 2;</code>
       * @param value The time to set.
       * @return This builder for chaining.
       */
      public Builder setTime(int value) {
        copyOnWrite();
        instance.setTime(value);
        return this;
      }
      /**
       * <code>uint32 time = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTime() {
        copyOnWrite();
        instance.clearTime();
        return this;
      }

      /**
       * <code>uint32 oldTime = 3;</code>
       * @return The oldTime.
       */
      @java.lang.Override
      public int getOldTime() {
        return instance.getOldTime();
      }
      /**
       * <code>uint32 oldTime = 3;</code>
       * @param value The oldTime to set.
       * @return This builder for chaining.
       */
      public Builder setOldTime(int value) {
        copyOnWrite();
        instance.setOldTime(value);
        return this;
      }
      /**
       * <code>uint32 oldTime = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearOldTime() {
        copyOnWrite();
        instance.clearOldTime();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:SystemTime.rsp_update_gmt_time_t)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new oplus.pb.SystemTime.rsp_update_gmt_time_t();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "type_",
              "time_",
              "oldTime_",
            };
            java.lang.String info =
                "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u000b\u0002\u000b" +
                "\u0003\u000b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<oplus.pb.SystemTime.rsp_update_gmt_time_t> parser = PARSER;
          if (parser == null) {
            synchronized (oplus.pb.SystemTime.rsp_update_gmt_time_t.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<oplus.pb.SystemTime.rsp_update_gmt_time_t>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:SystemTime.rsp_update_gmt_time_t)
    private static final oplus.pb.SystemTime.rsp_update_gmt_time_t DEFAULT_INSTANCE;
    static {
      rsp_update_gmt_time_t defaultInstance = new rsp_update_gmt_time_t();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        rsp_update_gmt_time_t.class, defaultInstance);
    }

    public static oplus.pb.SystemTime.rsp_update_gmt_time_t getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<rsp_update_gmt_time_t> PARSER;

    public static com.google.protobuf.Parser<rsp_update_gmt_time_t> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface rsp_read_sys_time_tOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SystemTime.rsp_read_sys_time_t)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>uint32 timeSource = 1;</code>
     * @return The timeSource.
     */
    int getTimeSource();

    /**
     * <code>uint32 type = 2;</code>
     * @return The type.
     */
    int getType();

    /**
     * <code>uint32 time = 3;</code>
     * @return The time.
     */
    int getTime();

    /**
     * <code>sint32 timezone = 4;</code>
     * @return The timezone.
     */
    int getTimezone();
  }
  /**
   * Protobuf type {@code SystemTime.rsp_read_sys_time_t}
   */
  public  static final class rsp_read_sys_time_t extends
      com.google.protobuf.GeneratedMessageLite<
          rsp_read_sys_time_t, rsp_read_sys_time_t.Builder> implements
      // @@protoc_insertion_point(message_implements:SystemTime.rsp_read_sys_time_t)
      rsp_read_sys_time_tOrBuilder {
    private rsp_read_sys_time_t() {
    }
    public static final int TIMESOURCE_FIELD_NUMBER = 1;
    private int timeSource_;
    /**
     * <code>uint32 timeSource = 1;</code>
     * @return The timeSource.
     */
    @java.lang.Override
    public int getTimeSource() {
      return timeSource_;
    }
    /**
     * <code>uint32 timeSource = 1;</code>
     * @param value The timeSource to set.
     */
    private void setTimeSource(int value) {
      
      timeSource_ = value;
    }
    /**
     * <code>uint32 timeSource = 1;</code>
     */
    private void clearTimeSource() {

      timeSource_ = 0;
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>uint32 type = 2;</code>
     * @return The type.
     */
    @java.lang.Override
    public int getType() {
      return type_;
    }
    /**
     * <code>uint32 type = 2;</code>
     * @param value The type to set.
     */
    private void setType(int value) {
      
      type_ = value;
    }
    /**
     * <code>uint32 type = 2;</code>
     */
    private void clearType() {

      type_ = 0;
    }

    public static final int TIME_FIELD_NUMBER = 3;
    private int time_;
    /**
     * <code>uint32 time = 3;</code>
     * @return The time.
     */
    @java.lang.Override
    public int getTime() {
      return time_;
    }
    /**
     * <code>uint32 time = 3;</code>
     * @param value The time to set.
     */
    private void setTime(int value) {
      
      time_ = value;
    }
    /**
     * <code>uint32 time = 3;</code>
     */
    private void clearTime() {

      time_ = 0;
    }

    public static final int TIMEZONE_FIELD_NUMBER = 4;
    private int timezone_;
    /**
     * <code>sint32 timezone = 4;</code>
     * @return The timezone.
     */
    @java.lang.Override
    public int getTimezone() {
      return timezone_;
    }
    /**
     * <code>sint32 timezone = 4;</code>
     * @param value The timezone to set.
     */
    private void setTimezone(int value) {
      
      timezone_ = value;
    }
    /**
     * <code>sint32 timezone = 4;</code>
     */
    private void clearTimezone() {

      timezone_ = 0;
    }

    public static oplus.pb.SystemTime.rsp_read_sys_time_t parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.SystemTime.rsp_read_sys_time_t parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.SystemTime.rsp_read_sys_time_t parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.SystemTime.rsp_read_sys_time_t parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.SystemTime.rsp_read_sys_time_t parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.SystemTime.rsp_read_sys_time_t parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.SystemTime.rsp_read_sys_time_t parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static oplus.pb.SystemTime.rsp_read_sys_time_t parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static oplus.pb.SystemTime.rsp_read_sys_time_t parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static oplus.pb.SystemTime.rsp_read_sys_time_t parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static oplus.pb.SystemTime.rsp_read_sys_time_t parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static oplus.pb.SystemTime.rsp_read_sys_time_t parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(oplus.pb.SystemTime.rsp_read_sys_time_t prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code SystemTime.rsp_read_sys_time_t}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          oplus.pb.SystemTime.rsp_read_sys_time_t, Builder> implements
        // @@protoc_insertion_point(builder_implements:SystemTime.rsp_read_sys_time_t)
        oplus.pb.SystemTime.rsp_read_sys_time_tOrBuilder {
      // Construct using oplus.pb.SystemTime.rsp_read_sys_time_t.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>uint32 timeSource = 1;</code>
       * @return The timeSource.
       */
      @java.lang.Override
      public int getTimeSource() {
        return instance.getTimeSource();
      }
      /**
       * <code>uint32 timeSource = 1;</code>
       * @param value The timeSource to set.
       * @return This builder for chaining.
       */
      public Builder setTimeSource(int value) {
        copyOnWrite();
        instance.setTimeSource(value);
        return this;
      }
      /**
       * <code>uint32 timeSource = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimeSource() {
        copyOnWrite();
        instance.clearTimeSource();
        return this;
      }

      /**
       * <code>uint32 type = 2;</code>
       * @return The type.
       */
      @java.lang.Override
      public int getType() {
        return instance.getType();
      }
      /**
       * <code>uint32 type = 2;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(int value) {
        copyOnWrite();
        instance.setType(value);
        return this;
      }
      /**
       * <code>uint32 type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        copyOnWrite();
        instance.clearType();
        return this;
      }

      /**
       * <code>uint32 time = 3;</code>
       * @return The time.
       */
      @java.lang.Override
      public int getTime() {
        return instance.getTime();
      }
      /**
       * <code>uint32 time = 3;</code>
       * @param value The time to set.
       * @return This builder for chaining.
       */
      public Builder setTime(int value) {
        copyOnWrite();
        instance.setTime(value);
        return this;
      }
      /**
       * <code>uint32 time = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTime() {
        copyOnWrite();
        instance.clearTime();
        return this;
      }

      /**
       * <code>sint32 timezone = 4;</code>
       * @return The timezone.
       */
      @java.lang.Override
      public int getTimezone() {
        return instance.getTimezone();
      }
      /**
       * <code>sint32 timezone = 4;</code>
       * @param value The timezone to set.
       * @return This builder for chaining.
       */
      public Builder setTimezone(int value) {
        copyOnWrite();
        instance.setTimezone(value);
        return this;
      }
      /**
       * <code>sint32 timezone = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimezone() {
        copyOnWrite();
        instance.clearTimezone();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:SystemTime.rsp_read_sys_time_t)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new oplus.pb.SystemTime.rsp_read_sys_time_t();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "timeSource_",
              "type_",
              "time_",
              "timezone_",
            };
            java.lang.String info =
                "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0000\u0000\u0001\u000b\u0002\u000b" +
                "\u0003\u000b\u0004\u000f";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<oplus.pb.SystemTime.rsp_read_sys_time_t> parser = PARSER;
          if (parser == null) {
            synchronized (oplus.pb.SystemTime.rsp_read_sys_time_t.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<oplus.pb.SystemTime.rsp_read_sys_time_t>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:SystemTime.rsp_read_sys_time_t)
    private static final oplus.pb.SystemTime.rsp_read_sys_time_t DEFAULT_INSTANCE;
    static {
      rsp_read_sys_time_t defaultInstance = new rsp_read_sys_time_t();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        rsp_read_sys_time_t.class, defaultInstance);
    }

    public static oplus.pb.SystemTime.rsp_read_sys_time_t getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<rsp_read_sys_time_t> PARSER;

    public static com.google.protobuf.Parser<rsp_read_sys_time_t> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface rsp_sync_summer_timezone_tOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SystemTime.rsp_sync_summer_timezone_t)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>uint32 supportSummerTimezone = 1;</code>
     * @return The supportSummerTimezone.
     */
    int getSupportSummerTimezone();

    /**
     * <code>sint32 timezone = 2;</code>
     * @return The timezone.
     */
    int getTimezone();
  }
  /**
   * Protobuf type {@code SystemTime.rsp_sync_summer_timezone_t}
   */
  public  static final class rsp_sync_summer_timezone_t extends
      com.google.protobuf.GeneratedMessageLite<
          rsp_sync_summer_timezone_t, rsp_sync_summer_timezone_t.Builder> implements
      // @@protoc_insertion_point(message_implements:SystemTime.rsp_sync_summer_timezone_t)
      rsp_sync_summer_timezone_tOrBuilder {
    private rsp_sync_summer_timezone_t() {
    }
    public static final int SUPPORTSUMMERTIMEZONE_FIELD_NUMBER = 1;
    private int supportSummerTimezone_;
    /**
     * <code>uint32 supportSummerTimezone = 1;</code>
     * @return The supportSummerTimezone.
     */
    @java.lang.Override
    public int getSupportSummerTimezone() {
      return supportSummerTimezone_;
    }
    /**
     * <code>uint32 supportSummerTimezone = 1;</code>
     * @param value The supportSummerTimezone to set.
     */
    private void setSupportSummerTimezone(int value) {
      
      supportSummerTimezone_ = value;
    }
    /**
     * <code>uint32 supportSummerTimezone = 1;</code>
     */
    private void clearSupportSummerTimezone() {

      supportSummerTimezone_ = 0;
    }

    public static final int TIMEZONE_FIELD_NUMBER = 2;
    private int timezone_;
    /**
     * <code>sint32 timezone = 2;</code>
     * @return The timezone.
     */
    @java.lang.Override
    public int getTimezone() {
      return timezone_;
    }
    /**
     * <code>sint32 timezone = 2;</code>
     * @param value The timezone to set.
     */
    private void setTimezone(int value) {
      
      timezone_ = value;
    }
    /**
     * <code>sint32 timezone = 2;</code>
     */
    private void clearTimezone() {

      timezone_ = 0;
    }

    public static oplus.pb.SystemTime.rsp_sync_summer_timezone_t parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.SystemTime.rsp_sync_summer_timezone_t parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.SystemTime.rsp_sync_summer_timezone_t parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.SystemTime.rsp_sync_summer_timezone_t parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.SystemTime.rsp_sync_summer_timezone_t parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.SystemTime.rsp_sync_summer_timezone_t parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.SystemTime.rsp_sync_summer_timezone_t parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static oplus.pb.SystemTime.rsp_sync_summer_timezone_t parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static oplus.pb.SystemTime.rsp_sync_summer_timezone_t parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static oplus.pb.SystemTime.rsp_sync_summer_timezone_t parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static oplus.pb.SystemTime.rsp_sync_summer_timezone_t parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static oplus.pb.SystemTime.rsp_sync_summer_timezone_t parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(oplus.pb.SystemTime.rsp_sync_summer_timezone_t prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code SystemTime.rsp_sync_summer_timezone_t}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          oplus.pb.SystemTime.rsp_sync_summer_timezone_t, Builder> implements
        // @@protoc_insertion_point(builder_implements:SystemTime.rsp_sync_summer_timezone_t)
        oplus.pb.SystemTime.rsp_sync_summer_timezone_tOrBuilder {
      // Construct using oplus.pb.SystemTime.rsp_sync_summer_timezone_t.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>uint32 supportSummerTimezone = 1;</code>
       * @return The supportSummerTimezone.
       */
      @java.lang.Override
      public int getSupportSummerTimezone() {
        return instance.getSupportSummerTimezone();
      }
      /**
       * <code>uint32 supportSummerTimezone = 1;</code>
       * @param value The supportSummerTimezone to set.
       * @return This builder for chaining.
       */
      public Builder setSupportSummerTimezone(int value) {
        copyOnWrite();
        instance.setSupportSummerTimezone(value);
        return this;
      }
      /**
       * <code>uint32 supportSummerTimezone = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSupportSummerTimezone() {
        copyOnWrite();
        instance.clearSupportSummerTimezone();
        return this;
      }

      /**
       * <code>sint32 timezone = 2;</code>
       * @return The timezone.
       */
      @java.lang.Override
      public int getTimezone() {
        return instance.getTimezone();
      }
      /**
       * <code>sint32 timezone = 2;</code>
       * @param value The timezone to set.
       * @return This builder for chaining.
       */
      public Builder setTimezone(int value) {
        copyOnWrite();
        instance.setTimezone(value);
        return this;
      }
      /**
       * <code>sint32 timezone = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimezone() {
        copyOnWrite();
        instance.clearTimezone();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:SystemTime.rsp_sync_summer_timezone_t)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new oplus.pb.SystemTime.rsp_sync_summer_timezone_t();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "supportSummerTimezone_",
              "timezone_",
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u000b\u0002\u000f" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<oplus.pb.SystemTime.rsp_sync_summer_timezone_t> parser = PARSER;
          if (parser == null) {
            synchronized (oplus.pb.SystemTime.rsp_sync_summer_timezone_t.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<oplus.pb.SystemTime.rsp_sync_summer_timezone_t>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:SystemTime.rsp_sync_summer_timezone_t)
    private static final oplus.pb.SystemTime.rsp_sync_summer_timezone_t DEFAULT_INSTANCE;
    static {
      rsp_sync_summer_timezone_t defaultInstance = new rsp_sync_summer_timezone_t();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        rsp_sync_summer_timezone_t.class, defaultInstance);
    }

    public static oplus.pb.SystemTime.rsp_sync_summer_timezone_t getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<rsp_sync_summer_timezone_t> PARSER;

    public static com.google.protobuf.Parser<rsp_sync_summer_timezone_t> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
