// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: widget.proto
// Protobuf Java Version: 4.28.2

package oplus.pb;

public final class Widget {
  private Widget() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface WidgetHROrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.heytap.wearable.health.WidgetHR)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>uint32 lastHeartRate = 1;</code>
     * @return The lastHeartRate.
     */
    int getLastHeartRate();

    /**
     * <code>uint32 timeStamp = 2;</code>
     * @return The timeStamp.
     */
    int getTimeStamp();
  }
  /**
   * Protobuf type {@code com.heytap.wearable.health.WidgetHR}
   */
  public  static final class WidgetHR extends
      com.google.protobuf.GeneratedMessageLite<
          WidgetHR, WidgetHR.Builder> implements
      // @@protoc_insertion_point(message_implements:com.heytap.wearable.health.WidgetHR)
      WidgetHROrBuilder {
    private WidgetHR() {
    }
    public static final int LASTHEARTRATE_FIELD_NUMBER = 1;
    private int lastHeartRate_;
    /**
     * <code>uint32 lastHeartRate = 1;</code>
     * @return The lastHeartRate.
     */
    @java.lang.Override
    public int getLastHeartRate() {
      return lastHeartRate_;
    }
    /**
     * <code>uint32 lastHeartRate = 1;</code>
     * @param value The lastHeartRate to set.
     */
    private void setLastHeartRate(int value) {
      
      lastHeartRate_ = value;
    }
    /**
     * <code>uint32 lastHeartRate = 1;</code>
     */
    private void clearLastHeartRate() {

      lastHeartRate_ = 0;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private int timeStamp_;
    /**
     * <code>uint32 timeStamp = 2;</code>
     * @return The timeStamp.
     */
    @java.lang.Override
    public int getTimeStamp() {
      return timeStamp_;
    }
    /**
     * <code>uint32 timeStamp = 2;</code>
     * @param value The timeStamp to set.
     */
    private void setTimeStamp(int value) {
      
      timeStamp_ = value;
    }
    /**
     * <code>uint32 timeStamp = 2;</code>
     */
    private void clearTimeStamp() {

      timeStamp_ = 0;
    }

    public static oplus.pb.Widget.WidgetHR parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.Widget.WidgetHR parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.Widget.WidgetHR parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.Widget.WidgetHR parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.Widget.WidgetHR parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.Widget.WidgetHR parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.Widget.WidgetHR parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static oplus.pb.Widget.WidgetHR parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static oplus.pb.Widget.WidgetHR parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static oplus.pb.Widget.WidgetHR parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static oplus.pb.Widget.WidgetHR parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static oplus.pb.Widget.WidgetHR parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(oplus.pb.Widget.WidgetHR prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code com.heytap.wearable.health.WidgetHR}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          oplus.pb.Widget.WidgetHR, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.heytap.wearable.health.WidgetHR)
        oplus.pb.Widget.WidgetHROrBuilder {
      // Construct using oplus.pb.Widget.WidgetHR.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>uint32 lastHeartRate = 1;</code>
       * @return The lastHeartRate.
       */
      @java.lang.Override
      public int getLastHeartRate() {
        return instance.getLastHeartRate();
      }
      /**
       * <code>uint32 lastHeartRate = 1;</code>
       * @param value The lastHeartRate to set.
       * @return This builder for chaining.
       */
      public Builder setLastHeartRate(int value) {
        copyOnWrite();
        instance.setLastHeartRate(value);
        return this;
      }
      /**
       * <code>uint32 lastHeartRate = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastHeartRate() {
        copyOnWrite();
        instance.clearLastHeartRate();
        return this;
      }

      /**
       * <code>uint32 timeStamp = 2;</code>
       * @return The timeStamp.
       */
      @java.lang.Override
      public int getTimeStamp() {
        return instance.getTimeStamp();
      }
      /**
       * <code>uint32 timeStamp = 2;</code>
       * @param value The timeStamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimeStamp(int value) {
        copyOnWrite();
        instance.setTimeStamp(value);
        return this;
      }
      /**
       * <code>uint32 timeStamp = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimeStamp() {
        copyOnWrite();
        instance.clearTimeStamp();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.heytap.wearable.health.WidgetHR)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new oplus.pb.Widget.WidgetHR();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "lastHeartRate_",
              "timeStamp_",
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u000b\u0002\u000b" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<oplus.pb.Widget.WidgetHR> parser = PARSER;
          if (parser == null) {
            synchronized (oplus.pb.Widget.WidgetHR.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<oplus.pb.Widget.WidgetHR>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.heytap.wearable.health.WidgetHR)
    private static final oplus.pb.Widget.WidgetHR DEFAULT_INSTANCE;
    static {
      WidgetHR defaultInstance = new WidgetHR();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        WidgetHR.class, defaultInstance);
    }

    public static oplus.pb.Widget.WidgetHR getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<WidgetHR> PARSER;

    public static com.google.protobuf.Parser<WidgetHR> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface WidgetPressureOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.heytap.wearable.health.WidgetPressure)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>uint32 timeStamp = 1;</code>
     * @return The timeStamp.
     */
    int getTimeStamp();

    /**
     * <code>uint32 lastStress = 2;</code>
     * @return The lastStress.
     */
    int getLastStress();
  }
  /**
   * Protobuf type {@code com.heytap.wearable.health.WidgetPressure}
   */
  public  static final class WidgetPressure extends
      com.google.protobuf.GeneratedMessageLite<
          WidgetPressure, WidgetPressure.Builder> implements
      // @@protoc_insertion_point(message_implements:com.heytap.wearable.health.WidgetPressure)
      WidgetPressureOrBuilder {
    private WidgetPressure() {
    }
    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private int timeStamp_;
    /**
     * <code>uint32 timeStamp = 1;</code>
     * @return The timeStamp.
     */
    @java.lang.Override
    public int getTimeStamp() {
      return timeStamp_;
    }
    /**
     * <code>uint32 timeStamp = 1;</code>
     * @param value The timeStamp to set.
     */
    private void setTimeStamp(int value) {
      
      timeStamp_ = value;
    }
    /**
     * <code>uint32 timeStamp = 1;</code>
     */
    private void clearTimeStamp() {

      timeStamp_ = 0;
    }

    public static final int LASTSTRESS_FIELD_NUMBER = 2;
    private int lastStress_;
    /**
     * <code>uint32 lastStress = 2;</code>
     * @return The lastStress.
     */
    @java.lang.Override
    public int getLastStress() {
      return lastStress_;
    }
    /**
     * <code>uint32 lastStress = 2;</code>
     * @param value The lastStress to set.
     */
    private void setLastStress(int value) {
      
      lastStress_ = value;
    }
    /**
     * <code>uint32 lastStress = 2;</code>
     */
    private void clearLastStress() {

      lastStress_ = 0;
    }

    public static oplus.pb.Widget.WidgetPressure parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.Widget.WidgetPressure parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.Widget.WidgetPressure parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.Widget.WidgetPressure parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.Widget.WidgetPressure parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.Widget.WidgetPressure parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.Widget.WidgetPressure parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static oplus.pb.Widget.WidgetPressure parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static oplus.pb.Widget.WidgetPressure parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static oplus.pb.Widget.WidgetPressure parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static oplus.pb.Widget.WidgetPressure parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static oplus.pb.Widget.WidgetPressure parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(oplus.pb.Widget.WidgetPressure prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code com.heytap.wearable.health.WidgetPressure}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          oplus.pb.Widget.WidgetPressure, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.heytap.wearable.health.WidgetPressure)
        oplus.pb.Widget.WidgetPressureOrBuilder {
      // Construct using oplus.pb.Widget.WidgetPressure.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>uint32 timeStamp = 1;</code>
       * @return The timeStamp.
       */
      @java.lang.Override
      public int getTimeStamp() {
        return instance.getTimeStamp();
      }
      /**
       * <code>uint32 timeStamp = 1;</code>
       * @param value The timeStamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimeStamp(int value) {
        copyOnWrite();
        instance.setTimeStamp(value);
        return this;
      }
      /**
       * <code>uint32 timeStamp = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimeStamp() {
        copyOnWrite();
        instance.clearTimeStamp();
        return this;
      }

      /**
       * <code>uint32 lastStress = 2;</code>
       * @return The lastStress.
       */
      @java.lang.Override
      public int getLastStress() {
        return instance.getLastStress();
      }
      /**
       * <code>uint32 lastStress = 2;</code>
       * @param value The lastStress to set.
       * @return This builder for chaining.
       */
      public Builder setLastStress(int value) {
        copyOnWrite();
        instance.setLastStress(value);
        return this;
      }
      /**
       * <code>uint32 lastStress = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastStress() {
        copyOnWrite();
        instance.clearLastStress();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.heytap.wearable.health.WidgetPressure)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new oplus.pb.Widget.WidgetPressure();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "timeStamp_",
              "lastStress_",
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u000b\u0002\u000b" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<oplus.pb.Widget.WidgetPressure> parser = PARSER;
          if (parser == null) {
            synchronized (oplus.pb.Widget.WidgetPressure.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<oplus.pb.Widget.WidgetPressure>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.heytap.wearable.health.WidgetPressure)
    private static final oplus.pb.Widget.WidgetPressure DEFAULT_INSTANCE;
    static {
      WidgetPressure defaultInstance = new WidgetPressure();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        WidgetPressure.class, defaultInstance);
    }

    public static oplus.pb.Widget.WidgetPressure getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<WidgetPressure> PARSER;

    public static com.google.protobuf.Parser<WidgetPressure> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface WidgetDailyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.heytap.wearable.health.WidgetDaily)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>uint32 timeStamp = 1;</code>
     * @return The timeStamp.
     */
    int getTimeStamp();

    /**
     * <code>uint32 steps = 2;</code>
     * @return The steps.
     */
    int getSteps();

    /**
     * <code>uint32 calories = 3;</code>
     * @return The calories.
     */
    int getCalories();

    /**
     * <code>uint32 exercise = 4;</code>
     * @return The exercise.
     */
    int getExercise();

    /**
     * <code>uint32 activeTimes = 5;</code>
     * @return The activeTimes.
     */
    int getActiveTimes();
  }
  /**
   * Protobuf type {@code com.heytap.wearable.health.WidgetDaily}
   */
  public  static final class WidgetDaily extends
      com.google.protobuf.GeneratedMessageLite<
          WidgetDaily, WidgetDaily.Builder> implements
      // @@protoc_insertion_point(message_implements:com.heytap.wearable.health.WidgetDaily)
      WidgetDailyOrBuilder {
    private WidgetDaily() {
    }
    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private int timeStamp_;
    /**
     * <code>uint32 timeStamp = 1;</code>
     * @return The timeStamp.
     */
    @java.lang.Override
    public int getTimeStamp() {
      return timeStamp_;
    }
    /**
     * <code>uint32 timeStamp = 1;</code>
     * @param value The timeStamp to set.
     */
    private void setTimeStamp(int value) {
      
      timeStamp_ = value;
    }
    /**
     * <code>uint32 timeStamp = 1;</code>
     */
    private void clearTimeStamp() {

      timeStamp_ = 0;
    }

    public static final int STEPS_FIELD_NUMBER = 2;
    private int steps_;
    /**
     * <code>uint32 steps = 2;</code>
     * @return The steps.
     */
    @java.lang.Override
    public int getSteps() {
      return steps_;
    }
    /**
     * <code>uint32 steps = 2;</code>
     * @param value The steps to set.
     */
    private void setSteps(int value) {
      
      steps_ = value;
    }
    /**
     * <code>uint32 steps = 2;</code>
     */
    private void clearSteps() {

      steps_ = 0;
    }

    public static final int CALORIES_FIELD_NUMBER = 3;
    private int calories_;
    /**
     * <code>uint32 calories = 3;</code>
     * @return The calories.
     */
    @java.lang.Override
    public int getCalories() {
      return calories_;
    }
    /**
     * <code>uint32 calories = 3;</code>
     * @param value The calories to set.
     */
    private void setCalories(int value) {
      
      calories_ = value;
    }
    /**
     * <code>uint32 calories = 3;</code>
     */
    private void clearCalories() {

      calories_ = 0;
    }

    public static final int EXERCISE_FIELD_NUMBER = 4;
    private int exercise_;
    /**
     * <code>uint32 exercise = 4;</code>
     * @return The exercise.
     */
    @java.lang.Override
    public int getExercise() {
      return exercise_;
    }
    /**
     * <code>uint32 exercise = 4;</code>
     * @param value The exercise to set.
     */
    private void setExercise(int value) {
      
      exercise_ = value;
    }
    /**
     * <code>uint32 exercise = 4;</code>
     */
    private void clearExercise() {

      exercise_ = 0;
    }

    public static final int ACTIVETIMES_FIELD_NUMBER = 5;
    private int activeTimes_;
    /**
     * <code>uint32 activeTimes = 5;</code>
     * @return The activeTimes.
     */
    @java.lang.Override
    public int getActiveTimes() {
      return activeTimes_;
    }
    /**
     * <code>uint32 activeTimes = 5;</code>
     * @param value The activeTimes to set.
     */
    private void setActiveTimes(int value) {
      
      activeTimes_ = value;
    }
    /**
     * <code>uint32 activeTimes = 5;</code>
     */
    private void clearActiveTimes() {

      activeTimes_ = 0;
    }

    public static oplus.pb.Widget.WidgetDaily parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.Widget.WidgetDaily parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.Widget.WidgetDaily parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.Widget.WidgetDaily parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.Widget.WidgetDaily parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.Widget.WidgetDaily parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.Widget.WidgetDaily parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static oplus.pb.Widget.WidgetDaily parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static oplus.pb.Widget.WidgetDaily parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static oplus.pb.Widget.WidgetDaily parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static oplus.pb.Widget.WidgetDaily parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static oplus.pb.Widget.WidgetDaily parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(oplus.pb.Widget.WidgetDaily prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code com.heytap.wearable.health.WidgetDaily}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          oplus.pb.Widget.WidgetDaily, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.heytap.wearable.health.WidgetDaily)
        oplus.pb.Widget.WidgetDailyOrBuilder {
      // Construct using oplus.pb.Widget.WidgetDaily.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>uint32 timeStamp = 1;</code>
       * @return The timeStamp.
       */
      @java.lang.Override
      public int getTimeStamp() {
        return instance.getTimeStamp();
      }
      /**
       * <code>uint32 timeStamp = 1;</code>
       * @param value The timeStamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimeStamp(int value) {
        copyOnWrite();
        instance.setTimeStamp(value);
        return this;
      }
      /**
       * <code>uint32 timeStamp = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimeStamp() {
        copyOnWrite();
        instance.clearTimeStamp();
        return this;
      }

      /**
       * <code>uint32 steps = 2;</code>
       * @return The steps.
       */
      @java.lang.Override
      public int getSteps() {
        return instance.getSteps();
      }
      /**
       * <code>uint32 steps = 2;</code>
       * @param value The steps to set.
       * @return This builder for chaining.
       */
      public Builder setSteps(int value) {
        copyOnWrite();
        instance.setSteps(value);
        return this;
      }
      /**
       * <code>uint32 steps = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSteps() {
        copyOnWrite();
        instance.clearSteps();
        return this;
      }

      /**
       * <code>uint32 calories = 3;</code>
       * @return The calories.
       */
      @java.lang.Override
      public int getCalories() {
        return instance.getCalories();
      }
      /**
       * <code>uint32 calories = 3;</code>
       * @param value The calories to set.
       * @return This builder for chaining.
       */
      public Builder setCalories(int value) {
        copyOnWrite();
        instance.setCalories(value);
        return this;
      }
      /**
       * <code>uint32 calories = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCalories() {
        copyOnWrite();
        instance.clearCalories();
        return this;
      }

      /**
       * <code>uint32 exercise = 4;</code>
       * @return The exercise.
       */
      @java.lang.Override
      public int getExercise() {
        return instance.getExercise();
      }
      /**
       * <code>uint32 exercise = 4;</code>
       * @param value The exercise to set.
       * @return This builder for chaining.
       */
      public Builder setExercise(int value) {
        copyOnWrite();
        instance.setExercise(value);
        return this;
      }
      /**
       * <code>uint32 exercise = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearExercise() {
        copyOnWrite();
        instance.clearExercise();
        return this;
      }

      /**
       * <code>uint32 activeTimes = 5;</code>
       * @return The activeTimes.
       */
      @java.lang.Override
      public int getActiveTimes() {
        return instance.getActiveTimes();
      }
      /**
       * <code>uint32 activeTimes = 5;</code>
       * @param value The activeTimes to set.
       * @return This builder for chaining.
       */
      public Builder setActiveTimes(int value) {
        copyOnWrite();
        instance.setActiveTimes(value);
        return this;
      }
      /**
       * <code>uint32 activeTimes = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearActiveTimes() {
        copyOnWrite();
        instance.clearActiveTimes();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.heytap.wearable.health.WidgetDaily)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new oplus.pb.Widget.WidgetDaily();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "timeStamp_",
              "steps_",
              "calories_",
              "exercise_",
              "activeTimes_",
            };
            java.lang.String info =
                "\u0000\u0005\u0000\u0000\u0001\u0005\u0005\u0000\u0000\u0000\u0001\u000b\u0002\u000b" +
                "\u0003\u000b\u0004\u000b\u0005\u000b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<oplus.pb.Widget.WidgetDaily> parser = PARSER;
          if (parser == null) {
            synchronized (oplus.pb.Widget.WidgetDaily.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<oplus.pb.Widget.WidgetDaily>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.heytap.wearable.health.WidgetDaily)
    private static final oplus.pb.Widget.WidgetDaily DEFAULT_INSTANCE;
    static {
      WidgetDaily defaultInstance = new WidgetDaily();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        WidgetDaily.class, defaultInstance);
    }

    public static oplus.pb.Widget.WidgetDaily getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<WidgetDaily> PARSER;

    public static com.google.protobuf.Parser<WidgetDaily> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface WidgetDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.heytap.wearable.health.WidgetData)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.com.heytap.wearable.health.WidgetHR lastHeartRate = 1;</code>
     * @return Whether the lastHeartRate field is set.
     */
    boolean hasLastHeartRate();
    /**
     * <code>.com.heytap.wearable.health.WidgetHR lastHeartRate = 1;</code>
     * @return The lastHeartRate.
     */
    oplus.pb.Widget.WidgetHR getLastHeartRate();

    /**
     * <code>.com.heytap.wearable.health.WidgetPressure widgetPressure = 2;</code>
     * @return Whether the widgetPressure field is set.
     */
    boolean hasWidgetPressure();
    /**
     * <code>.com.heytap.wearable.health.WidgetPressure widgetPressure = 2;</code>
     * @return The widgetPressure.
     */
    oplus.pb.Widget.WidgetPressure getWidgetPressure();

    /**
     * <code>.com.heytap.wearable.health.WidgetDaily widgetDaily = 3;</code>
     * @return Whether the widgetDaily field is set.
     */
    boolean hasWidgetDaily();
    /**
     * <code>.com.heytap.wearable.health.WidgetDaily widgetDaily = 3;</code>
     * @return The widgetDaily.
     */
    oplus.pb.Widget.WidgetDaily getWidgetDaily();
  }
  /**
   * Protobuf type {@code com.heytap.wearable.health.WidgetData}
   */
  public  static final class WidgetData extends
      com.google.protobuf.GeneratedMessageLite<
          WidgetData, WidgetData.Builder> implements
      // @@protoc_insertion_point(message_implements:com.heytap.wearable.health.WidgetData)
      WidgetDataOrBuilder {
    private WidgetData() {
    }
    private int bitField0_;
    public static final int LASTHEARTRATE_FIELD_NUMBER = 1;
    private oplus.pb.Widget.WidgetHR lastHeartRate_;
    /**
     * <code>.com.heytap.wearable.health.WidgetHR lastHeartRate = 1;</code>
     */
    @java.lang.Override
    public boolean hasLastHeartRate() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.com.heytap.wearable.health.WidgetHR lastHeartRate = 1;</code>
     */
    @java.lang.Override
    public oplus.pb.Widget.WidgetHR getLastHeartRate() {
      return lastHeartRate_ == null ? oplus.pb.Widget.WidgetHR.getDefaultInstance() : lastHeartRate_;
    }
    /**
     * <code>.com.heytap.wearable.health.WidgetHR lastHeartRate = 1;</code>
     */
    private void setLastHeartRate(oplus.pb.Widget.WidgetHR value) {
      value.getClass();
  lastHeartRate_ = value;
      bitField0_ |= 0x00000001;
      }
    /**
     * <code>.com.heytap.wearable.health.WidgetHR lastHeartRate = 1;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeLastHeartRate(oplus.pb.Widget.WidgetHR value) {
      value.getClass();
  if (lastHeartRate_ != null &&
          lastHeartRate_ != oplus.pb.Widget.WidgetHR.getDefaultInstance()) {
        lastHeartRate_ =
          oplus.pb.Widget.WidgetHR.newBuilder(lastHeartRate_).mergeFrom(value).buildPartial();
      } else {
        lastHeartRate_ = value;
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>.com.heytap.wearable.health.WidgetHR lastHeartRate = 1;</code>
     */
    private void clearLastHeartRate() {  lastHeartRate_ = null;
      bitField0_ = (bitField0_ & ~0x00000001);
    }

    public static final int WIDGETPRESSURE_FIELD_NUMBER = 2;
    private oplus.pb.Widget.WidgetPressure widgetPressure_;
    /**
     * <code>.com.heytap.wearable.health.WidgetPressure widgetPressure = 2;</code>
     */
    @java.lang.Override
    public boolean hasWidgetPressure() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.com.heytap.wearable.health.WidgetPressure widgetPressure = 2;</code>
     */
    @java.lang.Override
    public oplus.pb.Widget.WidgetPressure getWidgetPressure() {
      return widgetPressure_ == null ? oplus.pb.Widget.WidgetPressure.getDefaultInstance() : widgetPressure_;
    }
    /**
     * <code>.com.heytap.wearable.health.WidgetPressure widgetPressure = 2;</code>
     */
    private void setWidgetPressure(oplus.pb.Widget.WidgetPressure value) {
      value.getClass();
  widgetPressure_ = value;
      bitField0_ |= 0x00000002;
      }
    /**
     * <code>.com.heytap.wearable.health.WidgetPressure widgetPressure = 2;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeWidgetPressure(oplus.pb.Widget.WidgetPressure value) {
      value.getClass();
  if (widgetPressure_ != null &&
          widgetPressure_ != oplus.pb.Widget.WidgetPressure.getDefaultInstance()) {
        widgetPressure_ =
          oplus.pb.Widget.WidgetPressure.newBuilder(widgetPressure_).mergeFrom(value).buildPartial();
      } else {
        widgetPressure_ = value;
      }
      bitField0_ |= 0x00000002;
    }
    /**
     * <code>.com.heytap.wearable.health.WidgetPressure widgetPressure = 2;</code>
     */
    private void clearWidgetPressure() {  widgetPressure_ = null;
      bitField0_ = (bitField0_ & ~0x00000002);
    }

    public static final int WIDGETDAILY_FIELD_NUMBER = 3;
    private oplus.pb.Widget.WidgetDaily widgetDaily_;
    /**
     * <code>.com.heytap.wearable.health.WidgetDaily widgetDaily = 3;</code>
     */
    @java.lang.Override
    public boolean hasWidgetDaily() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.com.heytap.wearable.health.WidgetDaily widgetDaily = 3;</code>
     */
    @java.lang.Override
    public oplus.pb.Widget.WidgetDaily getWidgetDaily() {
      return widgetDaily_ == null ? oplus.pb.Widget.WidgetDaily.getDefaultInstance() : widgetDaily_;
    }
    /**
     * <code>.com.heytap.wearable.health.WidgetDaily widgetDaily = 3;</code>
     */
    private void setWidgetDaily(oplus.pb.Widget.WidgetDaily value) {
      value.getClass();
  widgetDaily_ = value;
      bitField0_ |= 0x00000004;
      }
    /**
     * <code>.com.heytap.wearable.health.WidgetDaily widgetDaily = 3;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeWidgetDaily(oplus.pb.Widget.WidgetDaily value) {
      value.getClass();
  if (widgetDaily_ != null &&
          widgetDaily_ != oplus.pb.Widget.WidgetDaily.getDefaultInstance()) {
        widgetDaily_ =
          oplus.pb.Widget.WidgetDaily.newBuilder(widgetDaily_).mergeFrom(value).buildPartial();
      } else {
        widgetDaily_ = value;
      }
      bitField0_ |= 0x00000004;
    }
    /**
     * <code>.com.heytap.wearable.health.WidgetDaily widgetDaily = 3;</code>
     */
    private void clearWidgetDaily() {  widgetDaily_ = null;
      bitField0_ = (bitField0_ & ~0x00000004);
    }

    public static oplus.pb.Widget.WidgetData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.Widget.WidgetData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.Widget.WidgetData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.Widget.WidgetData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.Widget.WidgetData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static oplus.pb.Widget.WidgetData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static oplus.pb.Widget.WidgetData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static oplus.pb.Widget.WidgetData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static oplus.pb.Widget.WidgetData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static oplus.pb.Widget.WidgetData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static oplus.pb.Widget.WidgetData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static oplus.pb.Widget.WidgetData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(oplus.pb.Widget.WidgetData prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code com.heytap.wearable.health.WidgetData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          oplus.pb.Widget.WidgetData, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.heytap.wearable.health.WidgetData)
        oplus.pb.Widget.WidgetDataOrBuilder {
      // Construct using oplus.pb.Widget.WidgetData.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>.com.heytap.wearable.health.WidgetHR lastHeartRate = 1;</code>
       */
      @java.lang.Override
      public boolean hasLastHeartRate() {
        return instance.hasLastHeartRate();
      }
      /**
       * <code>.com.heytap.wearable.health.WidgetHR lastHeartRate = 1;</code>
       */
      @java.lang.Override
      public oplus.pb.Widget.WidgetHR getLastHeartRate() {
        return instance.getLastHeartRate();
      }
      /**
       * <code>.com.heytap.wearable.health.WidgetHR lastHeartRate = 1;</code>
       */
      public Builder setLastHeartRate(oplus.pb.Widget.WidgetHR value) {
        copyOnWrite();
        instance.setLastHeartRate(value);
        return this;
        }
      /**
       * <code>.com.heytap.wearable.health.WidgetHR lastHeartRate = 1;</code>
       */
      public Builder setLastHeartRate(
          oplus.pb.Widget.WidgetHR.Builder builderForValue) {
        copyOnWrite();
        instance.setLastHeartRate(builderForValue.build());
        return this;
      }
      /**
       * <code>.com.heytap.wearable.health.WidgetHR lastHeartRate = 1;</code>
       */
      public Builder mergeLastHeartRate(oplus.pb.Widget.WidgetHR value) {
        copyOnWrite();
        instance.mergeLastHeartRate(value);
        return this;
      }
      /**
       * <code>.com.heytap.wearable.health.WidgetHR lastHeartRate = 1;</code>
       */
      public Builder clearLastHeartRate() {  copyOnWrite();
        instance.clearLastHeartRate();
        return this;
      }

      /**
       * <code>.com.heytap.wearable.health.WidgetPressure widgetPressure = 2;</code>
       */
      @java.lang.Override
      public boolean hasWidgetPressure() {
        return instance.hasWidgetPressure();
      }
      /**
       * <code>.com.heytap.wearable.health.WidgetPressure widgetPressure = 2;</code>
       */
      @java.lang.Override
      public oplus.pb.Widget.WidgetPressure getWidgetPressure() {
        return instance.getWidgetPressure();
      }
      /**
       * <code>.com.heytap.wearable.health.WidgetPressure widgetPressure = 2;</code>
       */
      public Builder setWidgetPressure(oplus.pb.Widget.WidgetPressure value) {
        copyOnWrite();
        instance.setWidgetPressure(value);
        return this;
        }
      /**
       * <code>.com.heytap.wearable.health.WidgetPressure widgetPressure = 2;</code>
       */
      public Builder setWidgetPressure(
          oplus.pb.Widget.WidgetPressure.Builder builderForValue) {
        copyOnWrite();
        instance.setWidgetPressure(builderForValue.build());
        return this;
      }
      /**
       * <code>.com.heytap.wearable.health.WidgetPressure widgetPressure = 2;</code>
       */
      public Builder mergeWidgetPressure(oplus.pb.Widget.WidgetPressure value) {
        copyOnWrite();
        instance.mergeWidgetPressure(value);
        return this;
      }
      /**
       * <code>.com.heytap.wearable.health.WidgetPressure widgetPressure = 2;</code>
       */
      public Builder clearWidgetPressure() {  copyOnWrite();
        instance.clearWidgetPressure();
        return this;
      }

      /**
       * <code>.com.heytap.wearable.health.WidgetDaily widgetDaily = 3;</code>
       */
      @java.lang.Override
      public boolean hasWidgetDaily() {
        return instance.hasWidgetDaily();
      }
      /**
       * <code>.com.heytap.wearable.health.WidgetDaily widgetDaily = 3;</code>
       */
      @java.lang.Override
      public oplus.pb.Widget.WidgetDaily getWidgetDaily() {
        return instance.getWidgetDaily();
      }
      /**
       * <code>.com.heytap.wearable.health.WidgetDaily widgetDaily = 3;</code>
       */
      public Builder setWidgetDaily(oplus.pb.Widget.WidgetDaily value) {
        copyOnWrite();
        instance.setWidgetDaily(value);
        return this;
        }
      /**
       * <code>.com.heytap.wearable.health.WidgetDaily widgetDaily = 3;</code>
       */
      public Builder setWidgetDaily(
          oplus.pb.Widget.WidgetDaily.Builder builderForValue) {
        copyOnWrite();
        instance.setWidgetDaily(builderForValue.build());
        return this;
      }
      /**
       * <code>.com.heytap.wearable.health.WidgetDaily widgetDaily = 3;</code>
       */
      public Builder mergeWidgetDaily(oplus.pb.Widget.WidgetDaily value) {
        copyOnWrite();
        instance.mergeWidgetDaily(value);
        return this;
      }
      /**
       * <code>.com.heytap.wearable.health.WidgetDaily widgetDaily = 3;</code>
       */
      public Builder clearWidgetDaily() {  copyOnWrite();
        instance.clearWidgetDaily();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.heytap.wearable.health.WidgetData)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new oplus.pb.Widget.WidgetData();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "lastHeartRate_",
              "widgetPressure_",
              "widgetDaily_",
            };
            java.lang.String info =
                "\u0000\u0003\u0000\u0001\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u1009\u0000\u0002" +
                "\u1009\u0001\u0003\u1009\u0002";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<oplus.pb.Widget.WidgetData> parser = PARSER;
          if (parser == null) {
            synchronized (oplus.pb.Widget.WidgetData.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<oplus.pb.Widget.WidgetData>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.heytap.wearable.health.WidgetData)
    private static final oplus.pb.Widget.WidgetData DEFAULT_INSTANCE;
    static {
      WidgetData defaultInstance = new WidgetData();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        WidgetData.class, defaultInstance);
    }

    public static oplus.pb.Widget.WidgetData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<WidgetData> PARSER;

    public static com.google.protobuf.Parser<WidgetData> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
